### ISSUE TITLE
Adding chgrp to the Dockerfile causes the HasModifiedFiles check in Preflight 1.6.5 to fail

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#1001]
## Bug Description
Adding chgrp on /usr/tmp to the Dockerfile causes the HasModifiedFiles check in Preflight 1.6.5 to fail.
I'm not sure if that's a bug, to be honest. Changing the ownership on /usr/tmp seems a bit strange but valid.

## Version and Command Invocation
1.6.5

##  Steps to Reproduce:

1. Build an image quay.io/tkrishtop/chgrp-example:v0.0.1 using the Dockerfile below:

```
FROM registry.access.redhat.com/ubi8/ubi:8.8-854

RUN chgrp -R 0 /usr/tmp && \
    chmod -R g=u /usr/tmp

CMD ["cat", "hello world"]
```

2. Run the Preflight check and observe the HasModifiedFiles check fail:

```
$ podman run -e PFLT_LOGLEVEL=trace quay.io/opdev/preflight:1.6.5 check container 
quay.io/tkrishtop/chgrp-example:v0.0.1
-- snip -- 
time="2023-06-07T11:23:19Z" level=debug msg="found disallowed modification in layer" 
file=usr/tmp layer="sha256:a7c537545914139085dd460c4f33d59f4f4c7bd1f4dbf89973e32bebd7555799"
time="2023-06-07T11:23:19Z" level=info msg="check completed" check=HasModifiedFiles result=FAILED
```

3. Initially /usr/tmp is a symlink coming from ubi8 base image

```
$ podman cp $(podman create --rm registry.access.redhat.com/ubi8/ubi:8.8-854 bash):/usr .
$ tree
--snip--
    ├── src
    │   ├── debug
    │   └── kernels
    └── tmp -> ../var/tmp
```

## Expected Result
Should HasModifiedFiles fail? Strictly speaking, we're not changing the file itself.

## Actual Result
check=HasModifiedFiles result=FAILED

## Additional Context
We are currently checking with the application guys on the partner side if these lines can be removed without harming the application.

cc: @bcrochet @acornett21

**Comment by bcrochet** [comment]
So, yes, a bug. Sort of. I would argue that if one would just change that to chmod /var/tmp instead of /usr/tmp, it would no longer fail, since we expect things in /var to change. Not sure what package owns that symlink (not really relevant), but I can see an argument for adding it to the exclusions, given it's usage as a temporary directory.
