### ISSUE TITLE
Build `preflight` without GLIBC

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/openshift-preflight#1015]
## Is your feature request related to a problem? Please describe.
We ran into an issue where the golang builder image updated to use a newer version of `glibc` then was in the UBI version of our base image. This lead to the below error.

```
preflight: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by preflight)
preflight: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by preflight)
```

## Describe the solution you'd like.
Preflight doesn't need to have a hard dependency on this `glibc` so we update the build process to no longer force this out the binary that we build.

## Describe alternatives you've considered.
NA

## Additional context.
```
 podman run -it --rm --entrypoint /bin/bash dbe46b5e0365
[root@20650cddbf6f /]# ldd /usr/local/bin/preflight 
/usr/local/bin/preflight: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/preflight)
/usr/local/bin/preflight: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/preflight)
        linux-vdso.so.1 (0x00007ffd53197000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4744802000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4744bc7000)
```

**Comment by itroyano** [comment]
#1020 may also be related to the Go 1.20 upgrade
