### ISSUE TITLE
latest preflight binaries fails to run on rhel8 machines with glibc error

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#1020]
## Bug Description
latest preflight binaries fails to run on rhel8 machines with glibc error
## Version and Command Invocation
(The output of `preflight --version`)

## Steps to Reproduce:
(How can we reproduce this?)
1) Download latest 1.6.8 preflight
2) Run the preflight on rhel8 mchine
3)

## Expected Result
Partner should be able to run preflight

## Actual Result
[root@dhcp210-254 viksss]# ./preflight-linux-amd64 -v
./preflight-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./preflight-linux-amd64)
./preflight-linux-amd64: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./preflight-linux-amd64)

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by itroyano** [comment]
May be related to the upgrade of the Go version we compile with -
https://github.com/redhat-openshift-ecosystem/openshift-preflight/commit/1f72aa2f5b111e1e201eadd89e11ad0ca4bc7310#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

@acornett21 Looks like Go is doing some linking that got resolved in the containerized version, when we upgraded to ubi9, but still needs to be resolved in the binary version.

@vikasmulaje as a temporary WA, should be possible to use the containerized Preflight.

**Comment by komish** [comment]
This is correct. As of Go 1.20, our binaries, which are dynamically linked, require equivalent libc available at the execution machine. The 1.20 Go build tooling seems to make different assumptions about CGO_ENABLED. For the time being, you can build off of main with CGO_ENABLED=0 which should work, but we haven't tested this yet. We'll likely move that direction, as the issue @itroyano links suggests.

**Comment by acornett21** [comment]
Closing this as duplicate, since we are already working on the other linked issue.
