### ISSUE TITLE
[Multi-ARCH] Preflight result submission fails when we submit for second time

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#1039]
## Bug Description
[Multi-ARCH] Preflight result submission fails when we submit for second time
## Version and Command Invocation
PR-997
## Steps to Reproduce:
(How can we reproduce this?)
1) Create a manifest list image
2) Submit result
3) Create New image tag and Submit results

## Expected Result
Partners should be able to submit results

## Actual Result
`Error: could not submit to pyxis: could not update project: status code: 400: body: {"detail": "The 'container.repository' field is immutable for projects with hosted registry", "status": 400, "title": "Bad Request", "type": "about:blank", "trace_id": "0x18173d0b0bb0ae455ac1558a14936b36"}
`

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by acornett21** [comment]
@vikasmulaje Are you sure the same image/registry was tested the 2nd time, this error comes from pyxis when the `repo` changes for the container under test.

**Comment by vikasmulaje** [comment]
Thanks @acornett21 This is fixed in next run on new project. Closing this
