### ISSUE TITLE
Add an overall status of a policy execution to the results output

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#106]
## Is your feature request related to a problem? Please describe.
Yes, users need to parse 3 check lists to evaluate whether their preflight execution was successful.

## Describe the solution you'd like.
Add a key in the results that reflects the overall state of the policy execution

## Describe alternatives you've considered.
N/A

## Additional context.
Implementation detail note - though all formatters get the Results in order to format them, we probably don't want them to do this evaluation at formatting time to reduce the likelihood of inconsistency.

**Comment by edreyer-1** [comment]
Question - what are the different statuses we would want? I was originally thinking we would have a passing, failure, error.  Would there be any others we would want?
