### ISSUE TITLE
Preflight check container fails with Error: failed to extract tarball: stream error: stream ID 41; INTERNAL_ERROR; received from peer

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#1072]
## Bug Description
Preflight check container fails Error: failed to extract tarball: stream error: stream ID 41; INTERNAL_ERROR; received from peer
## Version and Command Invocation
(The output of `preflight --version`)
preflight version 1.7.0-alpha1 <commit: fe9d181f888e2325fa0ae06b1374ed160a4fb925>

## Steps to Reproduce:
(How can we reproduce this?)
1) Create a manifest image
2) run preflight on that image
3)

## Expected Result
Preflight should run without any Error

## Actual Result
```
time="2023-10-03T03:56:53-04:00" level=debug msg="certification project" name=openshift-container-non-rhcc
time="2023-10-03T03:56:53-04:00" level=info msg="target image" image="quay.io/rhn_support_gsanwal/openshift-container-non-rhcc:0310.1256"
time="2023-10-03T03:56:53-04:00" level=debug msg="pulling image from target registry"
time="2023-10-03T03:56:53-04:00" level=trace msg="entering preflight keychain Resolve"
time="2023-10-03T03:56:59-04:00" level=debug msg="created temporary directory" path=/tmp/preflight-275486086
time="2023-10-03T03:56:59-04:00" level=debug msg="exporting and flattening image"
time="2023-10-03T03:56:59-04:00" level=debug msg="extracting container filesystem" path=/tmp/preflight-275486086/fs
time="2023-10-03T03:56:59-04:00" level=debug msg="writing container filesystem" outputDirectory=/tmp/preflight-275486086/fs
Error: failed to extract tarball: stream error: stream ID 41; INTERNAL_ERROR; received from peer
2023/10/03 03:57:25 failed to extract tarball: stream error: stream ID 41; INTERNAL_ERROR; received from peer
```

## Additional Context
Issue was consistent utill I did podman system prune and podman rmi -f -a
related issues: https://github.com/golang/go/issues/51323
https://github.com/googleapis/google-cloud-go/issues/784

**Comment by komish** [comment]
@vikasmulaje We tried to reproduce this and were unsuccessful. At the moment, we don't have enough detail here to be able to debug this level of issue given the level of variability here. If you're able to provide a more consistent approach to reproduce, please feel free to re-open this bug.
