### ISSUE TITLE
Image size is pretty big

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#108]
## Bug Description
`REPOSITORY                                 TAG                                        IMAGE ID       CREATED          SIZE

quay.io/opdev/preflight                    f07567b6bd629c2275bb2a2d9a39d502d31c5789   e6a85a623c42   34 seconds ago   **699MB**`

## Steps to Reproduce:
make image-build

**Comment by komish** [comment]
#241 might help with this.

**Comment by bcrochet** [comment]
What's our cutoff? I think we're down to 200M or so. Is that small enough?

**Comment by itroyano** [comment]
current image size is ~160Mb.  closing the issue.
