### ISSUE TITLE
Do not generate log file when running help sub-command

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/openshift-preflight#119]
## Bug Description

When running `preflight help`, an empty log file is created.

## Version and Command Invocation

```bash
$ ./preflight --version
preflight version 0.0.0 <commit: 2d3bb671bff8a95d385621382f31215234877d44>
```

## Steps to Reproduce:

1) Build the preflight binary locally: `make build` 
2) Run the help sub-command: `./preflight help`

## Expected Result

An empty log file should not be created when running the `help` sub-command.

## Actual Result

An empty log file named `preflight.log` is created.
```bash
ls -la preflight*
-rwxrwxr-x. 1 john john 11072372 Jul 21 10:07 preflight
-rw-------. 1 john john        0 Jul 21 10:08 preflight.log
```

## Additional Context

N/A

**Comment by komish** [comment]
This appears to be a regression: https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/30

**Comment by tonytcampbell** [comment]
Is this causing any issues rather than being slightly annoying?  I think we fixed this in the past by initializing the logging in each subcommand which caused the logging init code to be sprinkled in multiple places.  Having that code in multiple places seems more annoying.

**Comment by jomkz** [comment]
This is not causing any issues, it's just slightly annoying.

**Comment by acornett21** [comment]
This looks to be because `init()` is always called no matter the command passed in. I'll take a look at fixing this.
