### ISSUE TITLE
Write tests for the Golang bindings

### ISSUE THREAD

**Issue by OchiengEd** [redhat-openshift-ecosystem/openshift-preflight#125]
## Is your feature request related to a problem? Please describe.
No. This is to add test coverage for the golang bindings

## Describe the solution you'd like.
Add unit tests for the golang bindings in `certification/internal/bindings`

## Describe alternatives you've considered.
N/A

## Additional context.
N/A

**Comment by bcrochet** [comment]
This will not be necessary once deprecated code is removed. We are moving away from using podman and docker directly.
