### ISSUE TITLE
Add BDD tests for new scenarios

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#144]
## Is your feature request related to a problem? Please describe.
Increase coverage of BDD tests
## Describe the solution you'd like.
Adding new BDD tests for newly added scenarios
Ex: https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/52
## Describe alternatives you've considered.
(A clear and concise description of any alternative solutions or features you've considered.)

## Additional context.
(Add any other context or screenshots about the feature request here.)

**Comment by bcrochet** [comment]
Can we make these more specific? I like the idea of tracking the task, but without specifics, it will be hard to actually "close" this bug.

**Comment by komish** [comment]
IIRC The existing e2e tests _should_ be pulling in new checks as they get added. That said, some cases require more infrastructure than Github Actions currently have provisioned, which is currently the reason why we exclude them in our Actions.

+1 to what @bcrochet says. I'd like to see more scope definition here before implementation.

**Comment by jomkz** [comment]
@vikasmulaje Just going through older issues and wondered if we have an update on this?

**Comment by jomkz** [comment]
Closing this issue, as we should have decent test coverage in place for the checks. Please open a new issue if there is a specific area that needs better coverage.
