### ISSUE TITLE
Check for Related Images Schema Version 2 should use Podman Unshare and the Mounted Engine

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#149]
## Bug Description
We currently end up with an `extracted-bundle` directory that is coming from the operator check called `RelatedImagesAreSchemaVersion2`. 

This check currently "fake" runs the bundle in order to copy out the bundle to the caller filesystem. 

## Version and Command Invocation
`preflight check operator <operator-bundle>`

## Steps to Reproduce:
Run the above against a bundle of your choosing, and observe that the `extracted-bundle` directory exists on disk

## Expected Result
This check should instead leverage the mounted engine that is being used by other checks so that no assets have to be extracted from the bundle onto the host filesystem.

## Actual Result
Preflight extracts the bundle, and it also extracts it with the container's privileges and so frequently the host filesystem cannot delete the bundle without root privileges.

**Comment by bcrochet** [comment]
This is solved by moving to Crane in #174
