### ISSUE TITLE
Unable to build container image for preflight using Dockerfile

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#158]
## Bug Description
Unable to build container image for preflight using Dockerfile in repo
getting error
**Error: error creating build container: Digest of source image's manifest would not match destination reference**

## Version and Command Invocation
(The output of `preflight --version`)
preflight version 0.0.0 <commit: c99008db6e84f07999c3bc86de9b20f0189208e2>

[root@vikasmulaje openshift-preflight]# podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.8
OS/Arch:            linux/amd64

## Steps to Reproduce:
(How can we reproduce this?)
1) git clone preflight repo
2)cd openshift-preflight
3) podman build -t image_name .

## Expected Result
I should be able to build image from Dockerfile

## Actual Result
`[root@vikasmulaje tmp]# git clone https://github.com/redhat-openshift-ecosystem/openshift-preflight.git
Cloning into 'openshift-preflight'...
remote: Enumerating objects: 1547, done.
remote: Counting objects: 100% (337/337), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 1547 (delta 246), reused 230 (delta 216), pack-reused 1210
Receiving objects: 100% (1547/1547), 448.94 KiB | 317.00 KiB/s, done.
Resolving deltas: 100% (869/869), done.
[root@vikasmulaje tmp]# cd openshift-preflight/
[root@vikasmulaje openshift-preflight]# podman build -t viksss_aug11 .
STEP 1: FROM docker.io/library/golang@sha256:be99fa59acd78bb22a41bbc1e15ebfab2262498ee0c2e28c3d09bc44d51d1774 AS builder
STEP 2: COPY . /go/src/preflight
618c0fc5bd45b6306af3c15af33378faf3d3bb4bb695b9308e6b04cbf559266d
STEP 3: WORKDIR /go/src/preflight
7abddafc5377f2ba4cc1bd3c063c56dd59570ddf9d29df41a74a4b9fb4edfc60
STEP 4: RUN make build
go build -o preflight -ldflags "-X github.com/redhat-openshift-ecosystem/openshift-preflight/version.commit=e124799987f7596dac94b8e59d20d02975e285b4 -X github.com/redhat-openshift-ecosystem/openshift-preflight/version.version="0.0.0"" main.go
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/spf13/viper v1.8.1
go: downloading github.com/spf13/cobra v1.1.3
go: downloading github.com/knqyf263/go-rpmdb v0.0.0-20201215100354-a9e3110d8ee1
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/operator-framework/api v0.10.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading github.com/mitchellh/mapstructure v1.4.1
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/magiconair/properties v1.8.5
go: downloading github.com/pelletier/go-toml v1.9.3
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/spf13/afero v1.6.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading golang.org/x/sys v0.0.0-20210603081109-ebe580a85c40
go: downloading golang.org/x/text v0.3.6
go: downloading k8s.io/apiextensions-apiserver v0.21.1
go: downloading k8s.io/apimachinery v0.21.1
go: downloading k8s.io/api v0.21.1
go: downloading k8s.io/client-go v0.21.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/blang/semver v3.5.1+incompatible
go: downloading k8s.io/utils v0.0.0-20210527160623-6fdb442a123b
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/google/gofuzz v1.1.0
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.1.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/net v0.0.0-20210428140749-89ef3d95e781
go: downloading github.com/blang/semver/v4 v4.0.0
go: downloading k8s.io/klog/v2 v2.8.0
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/go-logr/logr v0.4.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading k8s.io/kube-openapi v0.0.0-20210305001622-591a79e4bda7
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d
go: downloading golang.org/x/oauth2 v0.0.0-20210402161424-2e8d93401602
go: downloading github.com/googleapis/gnostic v0.5.5
go: downloading google.golang.org/protobuf v1.26.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading github.com/golang/protobuf v1.5.2
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/go-restruct/restruct v0.0.0-20191227155143-5734170a48a1
go: downloading github.com/pkg/errors v0.9.1
ce8be8f74005f173f801099b36fff6b2ddeca835d4430be5e9d18eaf5fe9c2b0
STEP 5: FROM quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0
Error: error creating build container: Digest of source image's manifest would not match destination reference
`

## Additional Context
This works well when I use podman stable image quay.io/podman/stable

**Comment by bcrochet** [comment]
Are you able to pull that particular SHA?

**Comment by vikasmulaje** [comment]
No, getting same error
podman pull quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0
Trying to pull quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0...ERRO[0003] Error pulling image ref //quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0: Digest of source image's manifest would not match destination reference 
Failed
Error: error pulling image "quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0": unable to pull quay.io/podman/stable@sha256:c281b604477e10e3e84f81af9b68db59ee616bf6a34391224e5e5c74db0428d0: unable to pull image: Digest of source image's manifest would not match destination reference

It works well with podman stable image

**Comment by vikasmulaje** [comment]
I tried in two machines 
```
[root@vm40 openshift-preflight]# podman version
Version:            1.4.2-stable3
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
[root@vm40 openshift-preflight]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)
[root@vm40 openshift-preflight]# 
```

```
[root@vikasmulaje ~]# podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.8
OS/Arch:            linux/amd64
[root@vikasmulaje ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

This works well in fedora 34 vagrant box.
Can we please mention supported podman version in requirements and close this issue?
