### ISSUE TITLE
Ensure checks fall back to "failing" to avoid inadvertently passing a check

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#16]
In a given check's `Validate()` function, we should ensure that the logic checks for explicit cases indicating we've passed (and falling back to failing) instead of explicit cases indicating we've failed (and falling back to passing).

So for example, say we have this simplified method (pseudo-code) 

```go
func (s *SomeCheck) Validate() (bool, error) {
	data := s.runSomeCheckAndGetSomeData()
	
	hasFailed := s.evaluateDataForFailure(data) // returnings a bool
	
	if hasFailed {
		return false, nil
	}

	return true, nil
}
```

In this case, we check to see if we've failed. If we have, then we return `false` and fail the check. If, for whatever reason, `s.evaluateDataForFailure(data)` returns a false positive due to some error in our parsing (i.e. `hasFailed == false), then we'd pass the check by default.

Instead, I'm thinking we should encourage the inverse:

```go
func (s *SomeCheck) Validate() (bool, error) {
	data := s.runSomeCheckAndGetSomeData()
	
	hasPassed := s.evaluateDataForFailure(data) // returnings a bool
	
	if hasPassed {
		return true, nil
	}

	return false, nil
}
```

**Implementation Notes:**
Ex. where this is done according to the above example:
https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/ae9b2c7a5e78c092d574de7425392ce1a6faea89/certification/internal/shell/base_on_ubi.go#L47https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/certification/internal/shell/base_on_ubi.go#L47

We would want to replace checks that return true as their final line, as seen here:
https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/ae9b2c7a5e78c092d574de7425392ce1a6faea89/certification/internal/shell/has_license.go#L32

To fix this, we would have to go through and update existing checks to make sure that we look for explicit indicators of success and then return true in those cases (as opposed to looking for explicit indicators of failure and then returning false.

**Comment by edreyer-1** [comment]
@komish I think that there have been a decent number of updates since this issue was posted so I don't think there are many checks that still do this. The only one that I found that still does this was the HasRequiredLabel check. Were there any other checks that I am missing?

**Comment by komish** [comment]
Hey @edreyer-1, good catch. I'm only seeing one that needs addressing now. Here's the full list I checked, where unchecked means it needs addressing.

- [x] based_on_ubi
- [x] has_license
- [x] has_minimal_vulns
- [x] has_prohibited_packages
- [ ] has_required_labels
- [x] has_unique_tag
- [x] less_than_max_layers
- [x] runs_as_nonroot
- [x] scorecard_basic_check
- [x] scorecard_olm_suite
- [x] validate_operator_bundle
