### ISSUE TITLE
Add command line option -v -verbose to preflight

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#162]
## Is your feature request related to a problem? Please describe.
With current default log WARN we don't see any output when we run Preflight check for container/operator till the end result
for user it will look like command is stuck when on low network while downloading large images
## Describe the solution you'd like.
Add command line option -v(verbose) level which will override the default logging 
## Describe alternatives you've considered.
Current alternative is changing default logging at cmd/defaults.go to trace
## Additional context.
adding -v(verbose) will be easier for debugging and getting the current status of task in the background

**Comment by bcrochet** [comment]
You can also set PFLT_LOGLEVEL=trace. Is that sufficient?

**Comment by vikasmulaje** [comment]
Thanks @bcrochet that helps. It would really come handy if we add verbose in preflight cli in future.
is there any documentation for PFLT_* flags?

**Comment by komish** [comment]
@vikasmulaje This has been documented here: https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/docs/CONFIG.md. 

Does the PFLT_LOGLEVEL option resolve this issue sufficiently? I'm not sure we want to add flags for things that are already configurable in the environment.

**Comment by tkrishtop** [comment]
hi @vikasmulaje it seems like your request was covered in #281

**Comment by jomkz** [comment]
@vikasmulaje Just checking in to verify that the work done in #281, as well as the configurable log levels cover your use-case?
