### ISSUE TITLE
preflight fails to pull images from private registries if logged in with podman login registry

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#217]
## Bug Description
preflight will not pull images from private registries if logged in with podman login registry

## Version and Command Invocation
preflight version 0.0.0 <commit: a0cde2d821c8d29a15ac63c30c95252f18a0cfa5>
preflight check container registry.connect.redhat.com/mongodb/enterprise-database:latest
## Steps to Reproduce:
(How can we reproduce this?)
1) podman login registry.connect.redhat.com
2) preflight check container registry.connect.redhat.com/mongodb/enterprise-database:latest
3)

## Expected Result
Preflight should be able to pull the container images and run the checks

## Actual Result
`time="2021-09-08T09:27:49Z" level=fatal msg="failed to pull remote container: GET https://registry.connect.redhat.com/auth/realms/rhcc/protocol/redhat-docker-v2/auth?scope=repository%3Amongodb%2Fenterprise-database%3Apull&service=docker-registry: UNAUTHORIZED: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
`
## Additional Context
when user performs podman login it saves credentials in ${XDG_RUNTIME_DIR}/containers/auth.json
preflight checks credentials in $DOCKER_CONFIG/config.json (default: ~/.docker/config.json) to access images in private registries.
for more details check https://github.com/containers/podman/blob/main/docs/source/markdown/podman-login.1.md

**Comment by komish** [comment]
We rely on the `$DOCKER_CONFIG/config.json` path because underlying implementation details support this. We may consider supporting the ${XDG_RUNTIME_DIR}/containers/auth.json path in the future. In the meantime, however, you should be able to do something like:

```
ln -sf ${XDG_RUNTIME_DIR}/containers/auth.json ${XDG_RUNTIME_DIR}/containers/config.json
DOCKER_CONFIG=${XDG_RUNTIME_DIR}/containers
```

Should work?

**Comment by vikasmulaje** [comment]
Yes that works.
Can we document this till we implement it? I can see podman users are increasing day by day so it will be really hady for them if we add this
