### ISSUE TITLE
Is it possible to get junitxml output format back?  

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#268]
## Is your feature request related to a problem? Please describe.
In the past, preflight tool generated output both in json and junit. The plan was to use that while running preflight checks with DCI. DCI UI is able to parse junit and to display failed and passed tests in a nice way. 

Unfortunately, junit format was removed: https://github.com/redhat-openshift-ecosystem/openshift-preflight/commit/ee0ebc476e18714e4344c0a5ca58b1227966ff2a#diff-7b226e2c43cb28a869b02277ad5184ffce22c756fd9893e3b3109869e7eb50ed 

## Describe the solution you'd like.
Get junit format back directly in the preflight tool.

## Describe alternatives you've considered.
If it's impossible to do on preflight side, we'll probably have to parse preflight json output on DCI side.

**Comment by tkrishtop** [comment]
@komish opening an issue as discussed.

**Comment by bcrochet** [comment]
Is it sufficient to write to a junitxml file in the artifacts dir?

**Comment by tkrishtop** [comment]
hi @bcrochet 

> Is it sufficient to write to a junitxml file in the artifacts dir?

yes, that would be a perfect solution for our needs.

**Comment by bcrochet** [comment]
@tkrishtop Would love to get your feedback on the PR.
