### ISSUE TITLE
Have unique name for preflight.log to simplify subsequent tests for different operators in the same volume

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#274]
## Is your feature request related to a problem? Please describe.
I run in a row two `check container` and then one `check operator` in the same volume. Each test produces files named `preflight.log`, `results.json`, i.e. output file names are not unique. As a result, each test rewrites the results of the previous tests for _another_ container/operator.  

The issue is the same for all output files:
- preflight.log
- results.json
- results-junit.xml
- hashes.txt

## Describe the solution you'd like.
It would be nice to include name and tag into the name of each output file, i.e. to produce
`preflight_operator_testpmd-operator-bundle_v0.2.9_preflight.log` for `preflight check operator quay.io/rh-nfv-int/testpmd-operator-bundle:v0.2.9` (instead of `preflight.log`)
and
`preflight_container_cnf-test-partner_latest_results.json` for `preflight check container quay.io/testnetworkfunction/cnf-test-partner:latest` (instead of `results.json`)

## Describe alternatives you've considered.
For the moment I do this renaming after each test as a part of my DCI job but it would be nice to have it done on the preflight side.

**Comment by komish** [comment]
I believe that, by default, `preflight` should be writing to paths relative to `$PWD`. The preflight container, today, may having a working directory at `/` if I remember correctly.

Would either of the below work for you?
1) Making and `cd`ing to the directories before calling preflight, assuming you're not directly invoking our image but are instead using preflight in a script, or as a base image.
2) Setting `PFLT_ARTIFACTS` and` PFLT_LOGFILE` environment variables[1] to paths to which you can write?

Let us know.

[1]https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/docs/CONFIG.md#common-configuration

**Comment by tkrishtop** [comment]
Hi, @komish I see, thank you. Going to use `PFLT_ARTIFACTS` then.
