### ISSUE TITLE
Have --verbose and --wait-time flags exposed for operator-sdk scorecard inside preflight to simplify debug

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#275]
## Is your feature request related to a problem? Please describe.
I debug the scorecard command by preflight 
```
operator-sdk scorecard --output json --selector=test=basic-check-spec-test --kubeconfig /kubeconfig --namespace default --service-account default --config /tmp/scorecard-test-config-719719153.yaml /tmp/preflight-1476094131/fs
```

Here is the current error output I have, and it's not enough for me to debug properly. I'd like to have more logs and more time to connect to my cluster and check failing pods and their logs 

```
time="2021-09-28T10:08:50Z" level=trace msg="running scorecard with the following invocation[operator-sdk scorecard --output json --selector=test=basic-check-spec-test --kubeconfig /kubeconfig --namespace default --service-account default --config /tmp/scorecard-test-config-719719153.yaml /tmp/preflight-1476094131/fs]"
time="2021-09-28T10:09:20Z" level=error msg="stdout: "
time="2021-09-28T10:09:20Z" level=error msg="stderr: Error: error running tests context deadline exceeded\nUsage:\n  operator-sdk scorecard [flags]\n\nFlags:\n  -c, --config string            path to scorecard config file\n  -h, --help                     help for scorecard\n      --kubeconfig string        kubeconfig path\n  -L, --list                     Option to enable listing which tests are run\n  -n, --namespace string         namespace to run the test images in\n  -o, --output string            Output format for results. Valid values: text, json, xunit (default \"text\")\n  -l, --selector string          label selector to determine which tests are run\n  -s, --service-account string   Service account to use for tests (default \"default\")\n  -x, --skip-cleanup             Disable resource cleanup after tests are run\n  -t, --test-output string       Test output directory. (default \"test-output\")\n  -w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)\n\nGlobal Flags:\n      --plugins strings   plugin keys to be used for this subcommand execution\n      --verbose           Enable verbose logging\n\ntime=\"2021-09-28T10:09:20Z\" level=fatal msg=\"error running tests context deadline exceeded\"\n"
```

## Describe the solution you'd like.
I'd like to have:
- `--verbose` flag to be exposed to have more logs.
- `--wait-time` flag to be exposed to connect to my cluster and check pods status

## Describe alternatives you've considered.
Right now I have to run `operator-sdk scorecard` without preflight to use verbose and wait-time options.

**Comment by komish** [comment]
Adding the `--verbose` flag should be covered in #281.

The `--wait-time` seems reasonable as well, but it's not currently a preexisting configuration, so we'll need to look at this closer and see if there are other timeouts we need to synchronize for this test.

**Comment by tkrishtop** [comment]
Hi team, I was opening this issue while testing preflight v0.0.0, and my main concern was that the preflight was failing too fast for me to debug manually. Now, with preflight v1.0.3, I have an impression that all time-related concerns are managed in a better way, and I also found how to retrieve the logs from my cluster in an automated way during the preflight execution. 

So exposing the `--wait-time`  flag has no added value for me anymore, and we could close this feature request if it's ok for everyone.
