### ISSUE TITLE
preflight fails DeployableByOLM check for operator with installMode of AllNamespaces

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/openshift-preflight#293]
## Bug Description
When running `preflight check operator` against an operator that only has an installMode of `AllNamespaces` the DeployableByOLM check fails even though, this operator can be installed by OLM via the embedded OperatorHub.

## Version and Command Invocation
`preflight version 0.0.0 <commit: b11314a6b9603ba53d88826888c9856a738161b8>`

## Steps to Reproduce:
(How can we reproduce this?)
1) Run: `export PFLT_INDEXIMAGE="quay.io/acornett/elasticache-index-no-ad:v0.0.6"`
2) Run `preflight check operator quay.io/acornett/elasticache-controller-bundle-no-ad:v0.0.6`

## Expected Result
I expected this operator to be able to pass all checks, especially deployable by olm, since this operator can be installed via `operator-sdk` as well as via a the embedded OperatorHub. And that preflight can support any/all combinations of `installMode`

## Actual Result
The operator failed to install with the below error(s)
- `OwnNamespace InstallModeType not supported, cannot configure to watch own namespace`
- `UnsupportedOperatorGroup`

If you tail the logs of the olm operator, you'll get the below error
- For example `oc logs -f -n openshift-operator-lifecycle-manager olm-operator-`
- ```time="2021-10-15T15:42:20Z" level=info msg="installmodeset does not support operatorgroups namespace selection" csv=ack-elasticache-controller.v0.0.6 id=yMc9n namespace=ack-system phase=Failed reason="OwnNamespace InstallModeType not supported, cannot configure to watch own namespace"```

**Comment by samira-barouti** [comment]
Thank you Adam for opening this issue. Currently, preflight only supports OwnNamespace InstallMode. To support other types on InstallMode, the code needs to change to read the clusterserviceversion file and fetch all the supported InstallModes. The operator group's targetNamespace must be adjusted accordingly.

@tonytcampbell I was wondering If a CSV has multiple supported InstallModes, do we need to test for all the supported ones? This requires running the check, once per each supported InstallModes, which will increase the execution time.
