### ISSUE TITLE
[Check] Operator Bundle Data Linting

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#33]
Run `operator-sdk bundle validate -b podman --select-optional name=operatorhub --select-optional name=community registry.redhat.io/quay/quay-operator-bundle`  
Check should fail on errors and print to stdout and the log
Check should pass on warnings but print warnings to stdout and the log

**Comment by komish** [comment]
I think this is implemented already (see https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/certification/internal/shell/validate_operator_bundle.go#L15).

Can either @samira-barouti @bcrochet double check me and confirm we are good to close this?

**Comment by bcrochet** [comment]
I will take this, and fix up the existing check to use the interface.

/assign
