### ISSUE TITLE
Conditionally use `operatorframework.io/suggested-namespace` from the CSV as the `installedNamespace` when Running DeployableByOLM Check

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/openshift-preflight#331]
## Is your feature request related to a problem? Please describe.
Currently the value of `installedNamespace` comes for the `annotations.yaml` in some cases this might not be the most accurate namespace for an operator to be installed to. The CSV contains a more accurate field `operatorframework.io/suggested-namespace` where a given operator could be installed, if this key is present.

## Describe the solution you'd like.
Preflight is now parsing the CSV file for `installModes` I propose that if `operatorframework.io/suggested-namespace` is present in the CSV preflight uses this value for the installedNamespace to more closing align with how an operator with this field would be installed via the embedded OperatorHub UI when doing the DeployablebyOLM check.

## Describe alternatives you've considered.
N/A

## Additional context.
NA

_Originally posted by @acornett21 in https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/325#discussion_r742087693_

**Comment by komish** [comment]
Closing this as stale for the moment. If this feature is relevant to you, please re-open this issue.
