### ISSUE TITLE
Automatically test Preflight policy execution on pull request

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#336]
## Is your feature request related to a problem? Please describe.
Yes, currently there is no automated testing against new PRs that tests Preflight's functionality with the bugfix against a known good asset and a known supported OCP cluster version.

## Describe the solution you'd like.
Integrate with https://prow.ci.openshift.org's , consuming the ci-operator to claim a cluster of a version we support, and run against existing test assets.

## Describe alternatives you've considered.
- Standing up our own clusters (would require much more admimnistrator than consuming the mentioned platform)
- Standing up a single cluster per version and using task runners to target them in GH actions (less clean, higher likelihood of conflict)

## Additional context.
The work summary looks something like this:
- Enable openshift CI robots on our repositories so that the robots can perform automation on our behalf based on chat-ops commands (note: might conflict with our existing robots).
- Optionally enable merge robots to auto merge (we might not want this)
- Configure this repository in https://github.com/openshift/release to enable Prow plugins of interest (approve, lgtm, merge, etc)
- Define our Presubmit jobs, which should build binaries including the commits from the PR in scope
- Build and/or reuse any existing steps from the step registry to use the ci-operator and run our task. We could also embed our tests as scripts in this repository, and run those as our "steps" using this platform (instead of writing the entirety of the script in the test platform).
- Evaluate results to make sure everything passed, and otherwise just ensure preflight doesn't panic or fail with the change in question (note: these results will be public, but there should be little concern of credential leak because our test assets exist in public registries and don't require configuration or credentials themselves).

## Decisions/Requires Additional Input
|Pending Decision|
|---|
|**(Question)** Should this testing occur on every PR? What PRs should not be subject to this workflow (e.g  Docs PRs?) Can that level of filtering be automated?|
|**(Decision)** TBD|

|Pending Decision|
|---|
|**(Question)** Should we have different automation for releases? Tags? How does this automation differ?|
|**(Decision)** TBD|

|Pending Decision|
|---|
|**(Question)** Do we want to enable automatic merge using Tide|
|**(Decision)** TBD|

**Comment by vikasmulaje** [comment]
Hi @komish,
I am working on same scenario made some progress on build jenkins pipeline job and Preflight automation test.
Lets collaborate on this

**Comment by komish** [comment]
@vikasmulaje has started working on programmatically interacting with all of the current CLI endpoints. I think it makes sense to continue our existing integration with the Red Hat DPTP infrastructure because it gives us access to the on-demand openshift clusters, but I suggested @vikasmulaje submit his programmatic CLI testing code for review. If/when merged, we can replace my recently submitted bash script AND the existing e2e code base.

It should be a drop-in replacement, where we just change the `make test-e2e` target to run the test code instead of my bash scripts. 

Looking forward to the contributions @vikasmulaje!
