### ISSUE TITLE
Add a release action for semver tag builds

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#338]
For a released (X.Y.Z tagged) version,  we are currently building the artifacts and uploading to Quay.
A Github release action & release notes needs to be done manually.

We would like to generate a release with notes and description based on commits in this version vs. the previous.

In addition, to support pre-releases (Alpha, Beta, RC).

**Comment by jomkz** [comment]
@itroyano Have we thought any more about how we can address this one?

**Comment by itroyano** [comment]
generating release notes will be done using the existing "github release" method we are using currently.
there is an Action triggered by a release, to attach binaries.
closing this.
