### ISSUE TITLE
[Check] Operator Package Name Uniqueness 

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#34]
This check will require an API from the backend teams.  The API should accept a package name and return true if the name is unique (no other packages have that name) or false if the name is a duplicate of an existing package name in any of the catalogs

Need to work with the backend teams (CVP?) to have them create the API for us.

**Comment by rocrisp** [comment]
Pyxis has an operator interface. 

curl -X GET "https://catalog.redhat.com/api/containers/v1/operators/packages?include=data.package_name&page_size=500&page=1" -H  "accept: application/json"

I still need to get a grasp nf how to use the filter, but wondering if this is enough to get us started.

**Comment by rocrisp** [comment]
this command will return the operator in json format.
curl GET https://catalog.redhat.com/api/containers/v1/operators/packages?filter=package_name=="argocd-operator" -H  "accept: application/json"

{
  "data": [
    {
      "_id": "5e305ef85a1346687681e5a5",
      "association": "argocd-operator",
      "creation_date": "2020-01-28T16:19:04.819000+00:00",
      "last_update_date": "2020-01-28T16:19:04.819000+00:00",
      "package_name": "argocd-operator",
      "source": "community-operators"
    }
  ],
  "page": 0,
  "page_size": 100,
  "total": 1
}
