### ISSUE TITLE
Preflight attempts to run a v4.9 operator prior to checking for deprecated Kube 1.22/OpenShift 4.9 APIs

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/openshift-preflight#365]
## Bug Description

Preflight attempts to run a v4.9 operator prior to the check for deprecated Kubernetes 1.22/OpenShift 4.9 APIs.

This causes the Preflight test to waste several minutes waiting for the operator to become ready - when it's never going to happen.

After this finally fails the Kube 1.22 API test is run, which indeed fails and explains why the operator could not deploy.

## Version and Command Invocation
1.0.6

## Steps to Reproduce:
(How can we reproduce this?)
1) Run preflight on an operator that has v4.9 in its supported scope but has Kube 1.22 API violations.
2) 
3)

## Expected Result

Preflight will fail out the operator quickly after checking for Kube 1.22 API violations.

## Actual Result

Preflight wastes several minutes waiting for the operator to deploy (until the context deadline is exceeded), and only then runs the kube 1.22 API test.

## Additional Context

See attached log

[preflight2.log](https://github.com/redhat-openshift-ecosystem/openshift-preflight/files/7872181/preflight2.log)

**Comment by acornett21** [comment]
I'll let other chime in, but I'm not sure there is much that we can do about this. Preflight has to return a pass/fail for each check, which means we still have to run `DeployableByOLM` no matter what the `ValidateOperatorBundle` check produces.

**Comment by jfrancin** [comment]
Hmmm. I would argue that if we fail the ValidateOperatorBundle checks - especially the API check - the DeployableByOLM test should be skipped and marked Fail regardless.  The problem is that an API check failure will guarantee that the DeployableByOLM test _will_ fail. Why waste the resources and time in the test cluster if we already know this?

I can imagine that failing some of the other checks in ValidateOperatorBundle will not preclude a successful OLM deployment.  Perhaps the VOB check should set a flag to indicate that the DBO test should not be performed.

**Comment by samira-barouti** [comment]
@jfrancin We initially had a conversation around introducing dependencies between checks, and we decided to keep them independent to facilitate the concurrent execution (we don't run the check in parallel at the moment, but we designed the tool to support this).

**Comment by jfrancin** [comment]
hmmm.  I'd like to have @tonytcampbell weigh in on this - he requested that I file this ticket. I think that the issue is at least worth discussing.

**Comment by bcrochet** [comment]
PIcking this up. Approach is going to be to include a call to bundle validate before running DeployableByOLM, as well as during the actual bundle validate check. This will keep them separate, but still "fail fast" on DeployableByOLM, so that the cost of running bundle validate twice is far less than failing late in DeployableByOLM.
