### ISSUE TITLE
[Container Cert] Develop a Preflight Distribution Pipeline

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#371]
Partners will need to be able to download Preflight for on premise use during container certification.   
1. We need to build binaries as GitHub releases. There should be binary for each supported architecture. (amd64, ppc64le. s390x etc)
2. We need to create containers containing the binary and prepare for delivering them through HACBS (Aug/Sep timeframe) or CPaaS

**Comment by itroyano** [comment]
Sub-tasks:

- [ create a s390x build]
- [ ]

**Comment by itroyano** [comment]
@jomkz we currently have image builds for amd64 and ppc (contributed by @mayurwaghmode ).
We also have a multi-arch target in the Makefile (done by @acornett21 I think).

I'm working on consolidating the image build code into the "release" action + adding the binaries by invoking "make multi-arch" and packaging them + a way to publish the artifacts in the release page.

**Comment by jomkz** [comment]
We had a discussion around how we want to handle tagging the multi-arch images in quay. We decided on the following format: 

```
sha7+platform-arch
```

**sha7**: The short GitHub commit SHA
**platform**: The OS platorm (`linux` is currently the only supported platform)
**arch**: The architecture (`amd64`,`ppc64le`,`arm64`,`s390x`)

**Comment by itroyano** [comment]
PR #383 updated
