### ISSUE TITLE
[Container Cert] "RPM_list_successful" test must be able to deal with containers built with ubi*-micro base images

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/openshift-preflight#375]
[Problem]
At present the outgoing CVP scan will fail the RPM_list_successful test for containers built with the ubi*-micro base images - currently ubi8-micro for RHEL 8, soon ubi-micro for RHEL 9. 

They fail because ubi*micro base images do not have either the `rpm(8)` or `yum/dnf(8)` tools installed.

Note that while the rpm and dnf/yum tools are **not** installed, there is a full set of RPM database files in `/var/lib/rpm`.

[Desired solution]
Some means of ensuring that this test can be either

a) made to pass if the base image is indeed so built

OR

b) test is skipped if an alternative way to check it is not available

One thing that I can think of right off the bat would be to mount the Container Under Test's  filesystem and run the RPM or yum/dnf commands against the CUT's database instead of the enclosing {system/container}.

**Comment by lslebodn** [comment]
> One thing that I can think of right off the bat would be to mount the Container Under Test's filesystem and run the RPM or yum/dnf commands against the CUT's database instead of the enclosing {system/container}.

Different version of ubi contains different type of db as a backaend
```
[root@localhost ~]# docker create --name ubi-micro registry.access.redhat.com/ubi9-beta/ubi-micro:9.0.0beta-455
3d88a862fa989986cf2c8f3e7774c1fe69a338c005e0055ab412e1750c0895fd
[root@localhost ~]# rm -rf /tmp/data/rpm/
[root@localhost ~]# docker cp ubi-micro:/var/lib/rpm /tmp/data/rpm/
[root@localhost ~]# file /tmp/data/rpm/*
/tmp/data/rpm/rpmdb.sqlite:     SQLite 3.x database, last written using SQLite version 3034001
/tmp/data/rpm/rpmdb.sqlite-shm: data
/tmp/data/rpm/rpmdb.sqlite-wal: empty

[root@localhost ~]# docker rm ubi-micro
ubi-micro
[root@localhost ~]# docker create --name ubi-micro registry.access.redhat.com/ubi8-micro:8.5
d69d49dd3b8af596564cbadc390dc5d540b854f9d08f5581dfcfe95b30bb1959
[root@localhost ~]# rm -rf /tmp/data/rpm/
[root@localhost ~]# docker cp ubi-micro:/var/lib/rpm /tmp/data/rpm/
[root@localhost ~]# file /tmp/data/rpm/*
/tmp/data/rpm/Basenames:            Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Conflictname:         Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Dirnames:             Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Enhancename:          Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Filetriggername:      Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Group:                Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Installtid:           Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Name:                 Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Obsoletename:         Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Packages:             Berkeley DB (Hash, version 9, native byte-order)
/tmp/data/rpm/Providename:          Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Recommendname:        Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Requirename:          Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Sha1header:           Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Sigmd5:               Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Suggestname:          Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Supplementname:       Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Transfiletriggername: Berkeley DB (Btree, version 9, native byte-order)
/tmp/data/rpm/Triggername:          Berkeley DB (Btree, version 9, native byte-order)
```

It would be good to ensure you get expected results. Not sure how reliable would to use rpm/yum/dnf from "host"

BTW fortunately, there is not ubi7-micro. But there are still partners which certify images based on rhel7 based images

**Comment by jfrancin** [comment]
This would only be required for the ubi*-micro containers. There are no plans for RHEL 7 micro images - RHEL 7 will sail off into the sunset with the current set of base images, updated only for bugfixes. 

In other words, the situation in question here would not occur in a RHEL 7 container scenario.

I hadn't realized that RPM was shifting from BerkeleyDB to SQLite. I suspect that there are still ways to finesse this - the Fedora docs about the RPM update to use SQLite indicate that there are command line options to tell it to use the Berkeley DB info instead (and not automatically try to convert it). This will bear investigation, I suspect...

**Comment by bcrochet** [comment]
This is not really related to #25. #25 is about the base image, whereas this, IIUC, is about the actual RPM list.

I thought we had moved to checking against the rpmdb directly, and not using the rpm/dnf/yum commands. But if there is a move from BDB to SQLite, that would definitely make a difference to this one. I'll check on that.

**Comment by bcrochet** [comment]
In going through the CVP code, it looks like the RPM_List_Successful is just a bit of a "This is progressing fine". The use of the rpm executable does not appear to be central to the tests. I think we can close this, as any method that we use will not rely on the rpm executable in order to get a list of the RPMs installed in the container.

**Comment by lslebodn** [comment]
> In going through the CVP code, it looks like the RPM_List_Successful is just a bit of a "This is progressing fine". The use of the rpm executable does not appear to be central to the tests.

CVP extract list of rpms by using /bin/rpm binary
```
docker run --rm --entrypoint "rpm" $some image -qa --queryformat "%{NAME}|%{VERSION}|%{ARCH}|%{RELEASE}|%{SIGPGP:pgpsig}|%{SUMMARY}|%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}|%{EPOCH}|%{SOURCERPM}\n" > /home/centos/artifacts/container_rpms.txt
```
And than parse txt file into JSON like object. They are used on two places:
1) upload list of rpms to containerRpmManifestEntity pyxis(lightblie)
2) for the assesment `rpm_list_successful` . The assesment(check) will pass if there is nore than 1 rpm detected.

Extracting list of rpms with docker/podman run does not work with ubi-micro image cause /bin/rpm is not available there.
@jfrancin files a but to CVP to cover ubi-micro. CVP product owner decided to decrease priority of bug report due to capacity and changed focus to higher priority tasks.

I assume this is still valid and should be reopened.
But I let @jfrancin to decide.

**Comment by bcrochet** [comment]
We can do exactly those things, but going against the RPM database directly. We do not need the rpm binary itself for that. We are not implementing the rpm_list_successful directly in preflight.

**Comment by jfrancin** [comment]
So it would seem that this is a complete non-issue for the new Preflight, as long as it can handle either form of the RPM databases (RHEL 8 and prior, and RHEL 9).

As to the original ticket I filed on fixing this in the CVP, if the Preflight schedule stays on target for an April release, then I can leave the Jira ticket as it is; if the schedule is likely to slip into May or June it would make sense to do some sort of 'band-aid' fix to the CVP. 

John


--
John Francini
Sr. Certification Solutions Engineer
Partner Lifecycle Engineering - Certification Operations
Red Hat
Mobile: +1.603.661.0700
