### ISSUE TITLE
Preflight should fail if unsupported base image is used

### ISSUE THREAD

**Issue by jpaulovic** [redhat-openshift-ecosystem/openshift-preflight#379]
As discussed on Jan 20, preflight should extend the check of base image to verify that the rhel/ubi version used is not EOL.
cc @tonytcampbell

**Comment by jfrancin** [comment]
Note that this test is **not cut-and-dried** in certain cases. For example, if the partner is building an OpenStack plug-in, they will be using a base image that is likely deliberately built on top of an EUS version of a RHEL UBI. This is a valid use-case. The reported base image will be openstack-<component>-base. These are valid. Therefore the testing for base images will need to be not as simple as looking for ubi, ubi-{minimal,micro}.

There are also base images for Java middleware that are fully supported. Etc. The solution implemented here will need to cover all the bases [pun intended] to avoid cases.

**Comment by lslebodn** [comment]
The current implementation does exactly what @jfrancin described.
We do not care which base image was used. Whether it was a ubi base image or image for software collection in rhel7 or openstack, midleware one.
We just checked whether some RH base image could be found in pyxis. We used digest of unpacked layers for that.
```
        query($contImageLayers: [String!], $currentPage: Int){
            find_images(
                page: $currentPage
                filter: {
                     and: [
                        { repositories: { registry: { in: ["registry.redhat.io", "registry.access.redhat.com"] } } }
                        { uncompressed_top_layer_id: { in:  $contImageLayers  } }
                    ]
                }
            ){
              error {
                status
                detail
              }
              total
              page
              data{
    ...
```

**Comment by tonytcampbell** [comment]
GChat Thread where we discussed this:
https://chat.google.com/room/AAAAyhRf9po/y-U6GKqUF2I

**Comment by acornett21** [comment]
Partners have also found a way to _not_ use the latest UBI image to pass certification, so we should look into this more. Below is a sample of how they circumvented the process.

```
FROM previously-certified-image

user root
#update any of the packages that have vulnerabilities in the UBI image  
RUN yum update -y package1....packagen
user 1001:1001
```

**Comment by bcrochet** [comment]
> Note that this test is **not cut-and-dried** in certain cases. For example, if the partner is building an OpenStack plug-in, they will be using a base image that is likely deliberately built on top of an EUS version of a RHEL UBI. This is a valid use-case. The reported base image will be openstack--base. These are valid. Therefore the testing for base images will need to be not as simple as looking for ubi, ubi-{minimal,micro}.
> 
> There are also base images for Java middleware that are fully supported. Etc. The solution implemented here will need to cover all the bases [pun intended] to avoid cases.

We actually don't look for UBI specifically. What we do look for is that the image is based on a layer ID that we can get from pyxis, that lives in registry.access.redhat.com.

So, it should cover all RH images.
