### ISSUE TITLE
Remove HasMinimalVulnerabilitiesCheck

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/openshift-preflight#381]
## Is your feature request related to a problem? Please describe.

We need to remove the code that we have in place to perform the container image vulnerability check (HasMinimalVulnerabilitiesCheck). The current implementation only works for RHEL-8 based images and was disabled.

For container image certification, we are instead going to utilize Clair to scan the images once they have been pushed to a repository on [Quay](https://quay.io) and preflight will no longer include a vulnerability check.

## Describe the solution you'd like.

Remove the container vulnerability check functionality. 

## Additional context.

Further information can be found in #99.

**Comment by acornett21** [comment]
@bcrochet @jomkz Unless I'm missing something, I don't think this is in the code base anymore. There is nothing in the policies [here](https://github.com/redhat-openshift-ecosystem/openshift-preflight/tree/main/certification/internal/policy/container) or in the engine [here](https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/certification/engine/engine.go#L96-L104).

**Comment by jomkz** [comment]
I believe that this was fully removed when we migrated to crane engine, closing as there is nothing to do here.
