### ISSUE TITLE
Build Actions for `main` overwrite images in quay repo 

### ISSUE THREAD

**Issue by acornett21** [redhat-openshift-ecosystem/openshift-preflight#389]
## Bug Description
We have two build actions for main, one that should build/push and `amd64` and one that should push an `ppc64le`. The problem is both actions push to quay with a `sha` ie `quay.io/opdev/preflight:4712282207042438c017f37da42d2a775221fd88`. This means that whichever actions finishes 2nd, will be the only image that is present in quay for a given sha.

## Version and Command Invocation
N/A this is a workflow issue

## Steps to Reproduce:
1) merge code to main
2) see actions run
3) see one image published to quay
4) see that image get overwritten by the next action

## Expected Result
I'd expect to see two images in quay that are for different architectures. 

## Actual Result
There is only one image for one architecture see link to [quay](https://quay.io/repository/opdev/preflight/manifest/sha256:2bce1ec08a041e62af210c12b15c2695f1ff89424ecbd049857bffb9d7465643) for tag `4712282207042438c017f37da42d2a775221fd88`

## Additional Context
I think we need to make the tags unique for each image when we upload them to prevent this overwriting from happening. maybe update the below in the respective actions as a possible solution.
- `tags: ${{ github.sha }}-amd64`
-  `tags: ${{ github.sha }}-ppc64le`

**Comment by jomkz** [comment]
This issue has been addressed by #383
