### ISSUE TITLE
Preflight runtime-assets is broken since the first tag after 1.0.8 (1.0.8 is the last working)

### ISSUE THREAD

**Issue by tkrishtop** [redhat-openshift-ecosystem/openshift-preflight#392]
## Bug Description

To ensure the continuous work of Preflight-DCI integration, we're working on having daily tests for the Preflight main branch. For that, we test daily the last tag from https://quay.io/repository/opdev/preflight?tab=tags on five test operators.

We discovered that all tags after 1.0.8 have broken `preflight runtime-assets` behavior  (1.0.8 is the last working tag). The error is slightly different for RHEL 8.5 and for Fedora 34.

## Version and Command Invocation
All tags after 1.0.8 are broken, 1.0.8 is the last working tag

```
# broken tags
podman run -it --rm --pull=always quay.io/opdev/preflight:a4ab8565887dbb434fd0c8a7ad15903dd95f5fe3 runtime-assets
podman run -it --rm --pull=always quay.io/opdev/preflight:ppc64le runtime-assets
podman run -it --rm --pull=always quay.io/opdev/preflight:4712282207042438c017f37da42d2a775221fd88 runtime-assets
podman run -it --rm --pull=always quay.io/opdev/preflight:8db0dbb24fa8b899649ed67847960768f4da1312 runtime-assets

# the last working tag
podman run -it --rm --pull=always quay.io/opdev/preflight:1.0.8 runtime-assets
```

## Steps to Reproduce:
```
# broken for all tags after 1.0.8
# rhel 8.5
$ podman run -it --rm --pull=always quay.io/opdev/preflight:a4ab8565887dbb434fd0c8a7ad15903dd95f5fe3 runtime-assets
Trying to pull quay.io/opdev/preflight:a4ab8565887dbb434fd0c8a7ad15903dd95f5fe3...
Getting image source signatures
Copying blob 0d5389efd79f skipped: already exists  
Copying blob f6e1eb56b3e1 skipped: already exists  
Copying blob 426a35db26b1 skipped: already exists  
Copying config 333d1909a2 done  
Writing manifest to image destination
Storing signatures
standard_init_linux.go:228: exec user process caused: exec format error

# broken for all tags after 1.0.8
# Fedora 34
$ podman run -it --rm --pull=always quay.io/opdev/preflight:a4ab8565887dbb434fd0c8a7ad15903dd95f5fe3 runtime-assets
Trying to pull quay.io/opdev/preflight:a4ab8565887dbb434fd0c8a7ad15903dd95f5fe3...
Getting image source signatures
Copying blob 426a35db26b1 done  
Copying blob f6e1eb56b3e1 done  
Copying blob 0d5389efd79f done  
Copying config 333d1909a2 done  
Writing manifest to image destination
Storing signatures
{"msg":"exec container process `/usr/local/bin/preflight`: Exec format error","level":"error","time":"2022-02-07T09:16:08.000662041Z"}

# works for 1.0.8
$ podman run -it --rm --pull=always quay.io/opdev/preflight:1.0.8 runtime-assets
Trying to pull quay.io/opdev/preflight:1.0.8...
Getting image source signatures
Copying blob ad556179fa11 skipped: already exists  
Copying blob d4f13fad8263 skipped: already exists  
Copying blob 23fdb56daf15 skipped: already exists  
Copying config 56317c18f1 done  
Writing manifest to image destination
Storing signatures
{
    "images": [
        "quay.io/operator-framework/scorecard-test@sha256:c20b539ac6887f93175511da559f29a6b7601ed11826db32f04cb466e275918d"
    ]
}
```

## Expected Result
To have an image list as an output
```
{
    "images": [
        "quay.io/operator-framework/scorecard-test@sha256:c20b539ac6887f93175511da559f29a6b7601ed11826db32f04cb466e275918d"
    ]
}
```

## Actual Result
Preflight binary invocation error, different in RHEL 8.5 and Fedora 34
```
# RHEL 8.5
standard_init_linux.go:228: exec user process caused: exec format error

# Fedora 34
{"msg":"exec container process `/usr/local/bin/preflight`: Exec format error","level":"error","time":"2022-02-07T09:16:08.000662041Z"}
```

## Additional Context
It seems like the issue is caused by one of these commits 
![image](https://user-images.githubusercontent.com/26544656/152764654-6ce2cda2-5d13-4b78-b682-ca233edfd4b5.png)

**Comment by tkrishtop** [comment]
I've checked all these tags and seen that they were built for another arch: `ARCH=ppc64le`.

It seems like there is the ongoing implementation of multi-arch images [here](https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/371#issuecomment-1029118359), and there is an ongoing [fix](https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/391).

**Comment by lslebodn** [comment]
Or you can consider wrap all architectures into manifest v2 list.
* https://sdeoras.medium.com/special-case-of-building-multi-arch-container-images-distroless-go-and-podman-ad3e2ba0ccea
```
podman manifest create ${{ IMG }}:${{ env.SHA_SHORT }}

podman manifest add ${{IMG}}:${{ env.SHA_SHORT }}-${{ matrix.platform }}-amd64
podman manifest add ${{IMG}}:${{ env.SHA_SHORT }}-${{ matrix.platform }}-arm64
...
```

Similar approach described with docker. (not should which one do you use)
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by acornett21** [comment]
@lslebodn We have thought about that, but we also will be distributing `preflight` as a binary and not just a container to support `check container` certification process. So for now we are going to keep it one arch to one container.

**Comment by lslebodn** [comment]
> So for now we are going to keep it one arch to one container.

You still will/can have tags for arch specific container.
Manifest would be just a tiny simplification/enhancement.

But you should know what fits better to your use-cases/requirements/release workflow...

**Comment by itroyano** [comment]
Hi @tkrishtop,
please try now.
the tags have changed to reflect architecture, so the amd64 image from main would look like this: `quay.io/opdev/preflight:9f07a3a-linux-amd64`

**Comment by tkrishtop** [comment]
Hi @itroyano thank you for the PR, tested, everything seems to be fixed.
