### ISSUE TITLE
[Check] Operator Image Source

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#40]

**Comment by rocrisp** [comment]
I got this! 
Waiting on acceptance for https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/18
The 2 are not related but... just in case someone wants me to rewrite the whole thing.

**Comment by jomkz** [comment]
@tonytcampbell Just going through some old issues and wondering where we stand with this one?
