### ISSUE TITLE
Clearly indicate the overall check results.

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#403]
## Is your feature request related to a problem? Please describe.
The JSON output of Preflight contains the pass/fail results for all checks and an overall `passed` attribute that indicates if all the checks passed or not. 

## Describe the solution you'd like.
The overall attribute named `passed` is not clear enough.  We should rename it to `overall result` or something similar. 

## Describe alternatives you've considered.
(A clear and concise description of any alternative solutions or features you've considered.)

## Additional context.
(Add any other context or screenshots about the feature request here.)

**Comment by acornett21** [comment]
For `preflight` to implement this, we would need supporting changes in pyxis as well, since what `preflight` displays to the user is the payload that we send to `pyxis`.

**Comment by jomkz** [comment]
After discussing this a bit, we will log a message to `stderr` that indicates the overall result to make it more clear to the end user.
