### ISSUE TITLE
[Container Cert] Scratch image support

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#404]
In order to support a small population of scratch images when we come across a scratch image we will need to make a Pyxis call to read the os-content-type on the Project.  If the os-content-type is set to scratch then this Project has been approved to use scratch. If the Project has been approved to use scratch then we will bypass certain checks. 

- Skip the Base Image check

**Comment by bcrochet** [comment]
Fixed by #406
