### ISSUE TITLE
PodmanEngine should be an internal interface

### ISSUE THREAD

**Issue by bcrochet** [redhat-openshift-ecosystem/openshift-preflight#42]
Currently, the PodmanEngine interface is a public, exported interface. It really should be an internal interface.

Therefore, it should move to internal/cli as a package.

**Comment by komish** [comment]
@bcrochet Is this still relevant or can we close?

**Comment by bcrochet** [comment]
This should have closed with the code removal.

**Comment by bcrochet** [comment]
Fixed by #221
