### ISSUE TITLE
[Container Cert] Test Preflight with a container based on RHEL 9 to confirm it passes

### ISSUE THREAD

**Issue by tonytcampbell** [redhat-openshift-ecosystem/openshift-preflight#453]
Request from Product Management to test a RHEL 9 based container  with the new `preflight check container` flow and confirm that it works as expected.

**Comment by jpaulovic** [comment]
@tonytcampbell based on our yesterday's discussion I added this to the 1.1.0 milestone. Looks like y'all are already working on a fix in #456.

**Comment by acornett21** [comment]
- Relates: #456
