### ISSUE TITLE
Add initial behavior testing

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#46]
I think we can programmatically test behaviors of the application as a whole without necessarily calling out to the built binary by performing similar functions to what's done in the cobra `Run` commands.

## The Plan
* I'll find a "known good" and "known bad" container image and operator bundle
* build a `runtime.Config` using that image and our known defaults
* get the default engine
* run the checks
* parse the results

Similar to what we do here: https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/cmd/check_container.go#L24-L64

## The Test Case
The "known good" configuration should have no failed/errored entries in our results
The "known bad" configuration should have no successful/errored entries in our results

Down the road, we could expand this to be more granular, where we point to images that have known, specific failures and confirm that the results reflect that failure.

Logistically, I'd probably put this in a top-level `test` directory.

**Comment by komish** [comment]
cc: @bcrochet

**Comment by samira-barouti** [comment]
The UniqueTagCheck needs two good containers as well: one with only the `latest` tag, and one with `latest` AND other tags. So I believe we need at least 3 containers.

**Comment by bcrochet** [comment]
So, this sounds to me light e2e/integration testing, as opposed to unit testing. So, for this, I would definitely concur with the top-level test directory, and it being a separate package.

I think I'd like to see automation around building the known good/known bad images, pushing them to a public (quay.io) repository, then running the full tests based on those built images. Or, have a periodic build action (Does GH Actions support periodics? I would hope so...) that would build the images and push them to the registry. Then, the tests would just pull those down from a known location.

Overall, I like the concept.
