### ISSUE TITLE
Preflight must output the created containerImage _id to the user

### ISSUE THREAD

**Issue by jpaulovic** [redhat-openshift-ecosystem/openshift-preflight#465]
In order to enable partners in UAT to view test results in Connect, the partners will need to be able to construct a URL manually to get to specific image's test results in this format: `https://connect.uat.redhat.com/projects/{certProject._id}/images/{containerImage._id}/scan-results`

Preflight currently outputs a log such as
`time="2022-03-04T08:37:22Z" level=info msg="Please check https://connect.redhat.com/projects/6217d5887c6c194c4959ae10/overview to monitor the progress."`

We need to extend that to also output the containerImage._id so that the users in UAT can generate the URL mentioned above

cc @tonytcampbell

**Comment by acornett21** [comment]
We will just add this to the existing logic and always displaying `/scan-results` for all environments, we also need to change the below:

`log.Infof("The container's image id is: %s.", certImage.ImageID)` to

`log.Infof("The container's image id is: %s.", certImage.ID)
