### ISSUE TITLE
Submitting multiple times causes to receive a non 200 status code in getRPMManifest

### ISSUE THREAD

**Issue by tonyskapunk** [redhat-openshift-ecosystem/openshift-preflight#475]
## Bug Description
Submitting multiple times against QA causes a non 200 status:

1st submission: https://softwarefactory-project.io/paste/show/okWcp1ILOr7yxgEfpyAa/
subsequent submission: https://softwarefactory-project.io/paste/show/dGsj7BsN52jWLx0KFzEI/

We believe this PR was facing a similar scenario https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/442

## Version and Command Invocation
preflight version 0.0.0 <commit: ee1778decc7f4a3532b66d4918e5e20d90e3dfe8>

## Steps to Reproduce:
(How can we reproduce this?)
1) Submit multiple times the same check container
2)
3)

## Expected Result
(What did you expect to happen and why?)
Either not to fail or produce a more clear error message on the issue.

## Actual Result
(What actually happened)

excerpt of the issue:

```log
time="2022-03-10T12:21:38-06:00" level=debug msg="URL is: https://catalog.qa.redhat.com/api/containers/v1/images/id/6229cc021283cec915a92aa5/rpm-manifest"
time="2022-03-10T12:21:39-06:00" level=error msg="received non 200 status code in getRPMManifest: {\"detail\": \"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\", \"status\": 404, \"title\": \"Not Found\", \"type\": \"about:blank\", \"trace_id\": \"0x4fd53240aaef5fbdf4d870ac1e66441d\"}"
time="2022-03-10T12:21:39-06:00" level=error msg="error calling remote APIcould not get rpm manifest"
Error: error calling remote API
time="2022-03-10T12:21:39-06:00" level=fatal msg="error calling remote API"
```

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

Tests have been done against a QA environment.

cc: @tkrishtop

**Comment by acornett21** [comment]
Waiting on a response from the pyxis team why this URL isn't working.

**Comment by acornett21** [comment]
Pyxis isn't saving all the data we are sending them on for the `POST` call to create rpm manifest data, until that is fixed we can't be certain if there is an issue with the `GET` calls or not.

**Comment by acornett21** [comment]
Tested this against pyxis QA and it is working as expected. Hopefully this makes it to prod next Thursday. Adding the below Jira's for incase anyone wants to track the progress. Closing this defect against preflight, since we did not need to make any code changes.

https://issues.redhat.com/browse/ISV-1854
https://issues.redhat.com/browse/ISV-1855
