### ISSUE TITLE
preflight check container fails with error unexpected DB magic number: 3350644 for rhel9 images

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#480]
## Bug Description
preflight check container fails with error unexpected DB magic number: 3350644 for rhel9 images
## Version and Command Invocation
preflight version 0.0.0 <commit: 5bca0ef154242410ebc2bac600eedd6f11128aba>

## Steps to Reproduce:
(How can we reproduce this?)
1) preflight check container registry.redhat.io/ubi9-beta/dotnet-31:3.1-2
2)
3)

## Expected Result
preflight checks should run for rhel9 container images

## Actual Result
./preflight check container registry.redhat.io/ubi9-beta/dotnet-31:3.1-2 --pyxis-api-token XX --certification-project-id XX --pyxis-host catalog.qa.redhat.com/api/containers
time="2022-03-11T15:50:51+05:30" level=debug msg="config file not found, proceeding without it"
time="2022-03-11T15:50:51+05:30" level=info msg="certification library version 0.0.0 <commit: 5bca0ef154242410ebc2bac600eedd6f11128aba>"
time="2022-03-11T15:50:51+05:30" level=debug msg="URL is: https://catalog.qa.redhat.com/api/containers/v1/projects/certification/id/6217d5887c6c194c4959ae10"
time="2022-03-11T15:50:56+05:30" level=debug msg="Certification project name is: XX"
time="2022-03-11T15:50:56+05:30" level=debug msg="target image: registry.redhat.io/ubi9-beta/dotnet-31:3.1-2"
time="2022-03-11T15:50:56+05:30" level=debug msg="pulling image from target registry"
time="2022-03-11T15:50:59+05:30" level=debug msg="temporary directory is /tmp/preflight-685772835"
time="2022-03-11T15:50:59+05:30" level=debug msg="exporting and flattening image"
time="2022-03-11T15:50:59+05:30" level=debug msg="extracting container filesystem to /tmp/preflight-685772835/fs"
time="2022-03-11T15:50:59+05:30" level=debug msg="writing container filesystem to output dir: /tmp/preflight-685772835/fs"
time="2022-03-11T15:51:52+05:30" level=debug msg="getting tag info for image"
time="2022-03-11T15:51:52+05:30" level=trace msg="image config written to disk: /root/openshift-preflight/artifacts/cert-image.json"
Error: unexpected DB magic number: 3350644
time="2022-03-11T15:51:52+05:30" level=fatal msg="unexpected DB magic number: 3350644"

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by itroyano** [comment]
Seems to be thrown by the rpmdb library
https://github.com/knqyf263/go-rpmdb/blob/master/pkg/bdb/hash_metadata_page.go#L39

**Comment by itroyano** [comment]
@vikasmulaje is this tag a valid working image?
I can't seem to check package manager type on it...
`itroyano@itroyano-mac openshift-preflight % docker run -i registry.redhat.io/ubi9-beta/dotnet-31:3.1-2 "dnf --version"     
Error: Could not set cachedir: [Errno 28] No space left on device: '/var/tmp/dnf-default-5agkzb4a'
Exception ignored in: <function MainConf.__del__ at 0x7f64f9fb4940>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/conf/config.py", line 236, in __del__
    for file_name in self.tempfiles:
  File "/usr/lib/python3.9/site-packages/dnf/conf/config.py", line 67, in __getattr__
    option = getattr(self._config, name)
AttributeError: 'ConfigMain' object has no attribute 'tempfiles'`

**Comment by vikasmulaje** [comment]
@itroyano I was trying with images listed on catalog https://catalog.redhat.com/software/containers/search?q=ubi9&p=1&vendor_name=Red%20Hat

**Comment by itroyano** [comment]
@vikasmulaje yes but this command works when trying the latest tag of `ubi9-beta/ubi` for example - 

```
yum --version
4.7.0
  Installed: dnf-0:4.7.0-2.el9.noarch at Tue Oct 12 10:43:35 2021
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Mon Aug  9 20:32:04 2021

  Installed: rpm-0:4.16.1.3-7.el9.x86_64 at Tue Oct 12 10:43:34 2021
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Thu Aug 19 14:45:41 2021
```

is `ubi9-beta/dotnet-31` tag 3.1-2 a working image ?

**Comment by itroyano** [comment]
I'm also able to run `microdnf` from `ubi9-beta/ubi-minimal:latest`

is dotnet-31 different in terms of package management?

**Comment by acornett21** [comment]
I'm with @itroyano on this, if the image isn't runnable, then it can't be expected to work on preflight.

**Comment by itroyano** [comment]
@acornett21 I'm trying to find out what type of rpmdb the dotnet image uses.

current code for listing packages on a ubi9 based image, assumes an sqlite type rpmdb.
based on the error @vikasmulaje  got - this assumption isn’t true for dotnet-31 .
seems true for ubi and ubi-minimal though.

but when I try to check which db is used specifically here - I keep getting the error…

**Comment by vikasmulaje** [comment]
@itroyano @acornett21 yes, I can pull and run the image from the tag. I can see dnf installed on the image

**Comment by itroyano** [comment]
Thanks @vikasmulaje .
looks like it is a `rpmdb.sqlite`.

taking another look at `go-rpmdb`.

**Comment by bcrochet** [comment]
Should be fixed by #485

**Comment by acornett21** [comment]
Re-opening this issue, since we had to revert #485 since ppc64le isn't supported in [sqlite](https://pkg.go.dev/modernc.org/sqlite) library

**Comment by acornett21** [comment]
This was fixed in the below issue
- Relates: #531
