### ISSUE TITLE
[Doc or bug?] check container for non-UBI and non-RHEL based images

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#502]
Should `check container` support non-UBI or non-RHEL images?

```sh
preflight check container docker.io/alpine --pyxis-api-token XX  --certification-project-id XX --pyxis-host catalog.uat.redhat.com/api/containers
time="2022-03-21T01:39:41-07:00" level=info msg="certification library version 0.0.0 <commit: 06a9fd1520a37dc5b39328655f6ceaabf6471a51>"
Error: open /tmp/preflight-3153558342/fs/var/lib/rpm/Packages: no such file or directory
time="2022-03-21T01:39:44-07:00" level=fatal msg="open /tmp/preflight-3153558342/fs/var/lib/rpm/Packages: no such file or directory"
```

## Expected Result

An error stating only UBI and RHEL images are supported.  potentially with a doc link.
Or skip the packages check in case non-RHEL is actually intended to be supported.

**Comment by acornett21** [comment]
I think it's a given that we only support UBI/RHEL since one of the checks is `BasedOnUBI`, so I'm not sure more documentation is needed in `preflight` since there is documentation in gitbook/connect/etc.
