### ISSUE TITLE
change error message

### ISSUE THREAD

**Issue by yuriolisa** [redhat-openshift-ecosystem/openshift-preflight#530]
## Bug Description
Preflight is presenting the following error when we set an invalid `--pyxis-host` (i.e `catalog.uat.redhat.com/api/container` instead of `/containers`) .

## Version and Command Invocation
`preflight version 0.0.0 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>`

## Steps to Reproduce:
1) Run preflight check container with the wrong --pyxis-host parameter.

## Expected Result
As we are setting the wrong host parameter, we should report something like : 

`msg=invalid response when querying pyxis. please check the input pyxis host`

## Actual Result
````
 preflight check container XX:v0.22.4ubi --pyxis-api-token xx --certification-project-id xx  --pyxis-host catalog.uat.redhat.com/api/container

time="2022-03-30T10:04:56+02:00" level=info msg="certification library version 0.0.0 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>"
time="2022-03-30T10:04:56+02:00" level=error msg="invalid character '<' looking for beginning of value"
time="2022-03-30T10:04:56+02:00" level=error msg="invalid character '<' looking for beginning of valuecould not retrieve project"
Error: invalid character '<' looking for beginning of value
````

**Comment by itroyano** [comment]
being addressed by https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/566
we'll be simplifying the pyxis url input, and assuming that if the user does actually provides a url - overriding default - he knows what he's doing.

@yuriolisa @jomkz @bcrochet does this sound ok?
if so - can this issue be closed when the PR is merged?

**Comment by bcrochet** [comment]
Maybe. Part of the problem is that it isn't that the host is bad. It's the path. We may be getting a 404 in that case, so we may need to handle 404 better.

**Comment by acornett21** [comment]
- Relates: #653
