### ISSUE TITLE
RunAsNonRoot" result=FAILED

### ISSUE THREAD

**Issue by yossig-aquasec** [redhat-openshift-ecosystem/openshift-preflight#546]
## Bug Description
Hi, in the old scanning mechanism we are passing the RunAsNonRoot tests, but falling in the Preflight tool 
we ran the testes on the same image:

![image](https://user-images.githubusercontent.com/82142290/161695961-a3349f25-f7d7-4c56-b902-53be6c18c8f2.png)

Preflight command:
`preflight check container registry.aquasec.com/console:6.2.22087-ubi8 --pyxis-api-token=<redacted> --certification-project-id=ospid-624175a94453dea66774340e --docker-config=~/.docker/config.json --pyxis-host catalog.uat.redhat.com/api/containers`

results:

`time="2022-04-04T12:29:20Z" level=info msg="certification library version 1.1.0-beta6 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>"
time="2022-04-04T12:37:37Z" level=info msg="check completed: HasLicense" result=PASSED
time="2022-04-04T12:37:38Z" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-04-04T12:37:38Z" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-04-04T12:37:38Z" level=info msg="check completed: HasNoProhibitedPackagesMounted" result=PASSED
time="2022-04-04T12:37:38Z" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-04-04T12:37:38Z" level=info msg="check completed: RunAsNonRoot" result=FAILED
time="2022-04-04T12:37:46Z" level=info msg="check completed: BasedOnUbi" result=PASSED
time="2022-04-04T12:41:43Z" level=info msg="check completed: HasModifiedFiles" result=PASSED`
## Version and Command Invocation
preflight version 1.1.0-beta6 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>

## Steps to Reproduce:
(How can we reproduce this?)
1)
2)
3)

## Expected Result
Success: Same as old mechanism

## Actual Result
Failed on RunAsNonRoot test

**Comment by bcrochet** [comment]
Does your Dockerfile contain a USER statement? Without that, you will fail this check. This is as designed. Running a container without a USER directive will result in root.
