### ISSUE TITLE
failed to read docerconfig file when running the commmand with --submit

### ISSUE THREAD

**Issue by yossig-aquasec** [redhat-openshift-ecosystem/openshift-preflight#547]
## Bug Description
when running the command with `--submit` it failed to get docker config file.
example:
```root@9976247cd230:/# sudo preflight check container registry.aquasec.com/console:6.2.22087-ubi8 --submit --pyxis-api-token=7s5vtau0zck7czdeq1lcpo70th7zc1xn --certification-project-id=ospid-624175a94453dea66774340e --docker-config=~/.docker/config.json --pyxis-host catalog.uat.redhat.com/api/containers
time="2022-04-05T07:54:28Z" level=info msg="certification library version 1.1.0-beta6 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>"
Error: open ~/.docker/config.json: no such file or directory
Usage:
  preflight check container [flags]

Examples:
  preflight check container quay.io/repo-name/container-name:version

Flags:
      --certification-project-id string   Certification Project ID from conenct.redhat.com. Should be supplied without the ospid- prefix.
  -d, --docker-config string              path to docker config.json file
  -h, --help                              help for container
      --pyxis-api-token string            API token for Pyxis authentication
      --pyxis-host string                 Host to use for Pyxis submissions. (default "catalog.redhat.com/api/containers")
  -s, --submit                            submit check container results to red hat

Global Flags:
  -l, --list-checks   lists all the checks run for a given check

time="2022-04-05T07:54:32Z" level=fatal msg="open ~/.docker/config.json: no such file or directory"
```

but, when running the same command without `--submit` it works

## Version and Command Invocation
preflight version 1.1.0-beta6 <commit: https://github.com/redhat-openshift-ecosystem/openshift-preflight/commit/2ebe87409fcc9333149511466fdb452ccb88ad44>

## Steps to Reproduce:
run check container with\out `--submit`

## Expected Result
both will success

## Actual Result
when running the command with `--submit` it failed to get docker config file.

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by acornett21** [comment]
@yossig-aquasec This should be the full path to the `config.json` ie `/Users/yossig-aquasec/.docker/config.json` or ` ${XDG_RUNTIME_DIR}/containers/auth.json`

**Comment by yossig-aquasec** [comment]
Hi, the command with `--submit` option was succeeded when I used the full user path instead of ~/
but why its not aligned with the command without `--submit`?
if its work without `--submit` its should work the same with `--submit`

**Comment by acornett21** [comment]
@yossig-aquasec That argument is only invoked when `--submit` is passed in, in all other cases it is ignored and not used. I hope that helps clarify.

**Comment by yossig-aquasec** [comment]
@acornett21 sorry, but if I Don't add it to the command (without --submit) it will fail to download the image for scanning

**Comment by acornett21** [comment]
@yossig-aquasec Without `docker-config` flag set, `preflight` can still pull the image properly. The `docker-config` is only used in the submit flow to send the docker config file to Red Hat systems. If you remove `--submit` and `--docker-config ` flags preflight can still pull the images since the library we use to pull the image looks int he default location.

**Comment by yossig-aquasec** [comment]
Thanks for the explanation, I will try and update if something will fail
