### ISSUE TITLE
Observed error while running preflight

### ISSUE THREAD

**Issue by anildhaneshwar** [redhat-openshift-ecosystem/openshift-preflight#551]
Hi,

We are getting below error while running preflight tool.

# sudo podman login -u unused scan.connect.uat.redhat.com
Password:
Error: authenticating creds for "scan.connect.uat.redhat.com": error pinging docker registry scan.connect.uat.redhat.com: Get "[https://scan.connect.uat.redhat.com/v2/":](https://scan.connect.uat.redhat.com/v2/%22:) dial tcp: lookup scan.connect.uat.redhat.com on 10.80.120.208:53: no such host

Can anyone please have a look and suggest on same ?

Thanks,
Anil Dhaneshwar

**Comment by acornett21** [comment]
Hi @anildhaneshwar the inbound certification registry is not available in UAT. In the beta docs [here](https://github.com/redhat-openshift-ecosystem/certification-releases/blob/main/containers/beta-workflow.md) it states that images should be pushed to production.

```
In order to test the certification of your container, 
you must first push it to Red Hat's inbound certification registry (the production version, not UAT)
```

**Comment by anildhaneshwar** [comment]
Thanks @acornett21 ! We are getting new error now.

--- 
$ PFLT_PYXIS_HOST=catalog.uat.redhat.com/api/containers
$ preflight check container scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64 --pyxis-api-token=c4o3330rb15emg21xztlzxs3n9yf4fa8 --certification-project-id=624aaedabe4dd77dc8638007
INFO[0000] certification library version 0.0.0 <commit: 478d6d7db0afac422c122e1a8800760fd6426a6c>
ERRO[0000] received non 200 status code in GetProject: {"detail": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.", "status": 401, "title": "Unauthorized", "type": "about:blank", "trace_id": "0xd9d6b0ad6b952a1b63a3db77bdf5ba11"}
ERRO[0000] error calling remote APIcould not retrieve project
Error: error calling remote API
Usage:
preflight check container [flags]



Examples:
preflight check container quay.io/repo-name/container-name:version


Flags:
--certification-project-id string Certification Project ID from connect.redhat.com. Should be supplied without the ospid- prefix.
-d, --docker-config string path to docker config.json file
-h, --help help for container
--pyxis-api-token string API token for Pyxis authentication
--pyxis-host string Host to use for Pyxis submissions. (default "catalog.redhat.com/api/containers")
-s, --submit submit check container results to red hat


Global Flags:
-l, --list-checks lists all the checks run for a given check


FATA[0000] error calling remote API

---

Could you please have a look into it ?

Thanks,
Anil Dhaneshwar

**Comment by acornett21** [comment]
@anildhaneshwar The API ket needs to come from UAT as well. If the project and api key do not match you will get this error. See the below URL to create a UAT api-key.

https://connect.uat.redhat.com/account/api-keys
