### ISSUE TITLE
 getting error while running preflight tool

### ISSUE THREAD

**Issue by anildhaneshwar** [redhat-openshift-ecosystem/openshift-preflight#557]
We are getting new error while running preflight tool.

$ PFLT_PYXIS_HOST=catalog.uat.redhat.com/api/containers
$ preflight check container scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64 --pyxis-api-token=c4o3330rb15emg21xztlzxs3n9yf4fa8 --certification-project-id=624aaedabe4dd77dc8638007
INFO[0000] certification library version 0.0.0 <commit: https://github.com/redhat-openshift-ecosystem/openshift-preflight/commit/478d6d7db0afac422c122e1a8800760fd6426a6c>
ERRO[0000] received non 200 status code in GetProject: {"detail": "The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.", "status": 401, "title": "Unauthorized", "type": "about:blank", "trace_id": "0xd9d6b0ad6b952a1b63a3db77bdf5ba11"}
ERRO[0000] error calling remote APIcould not retrieve project
Error: error calling remote API
Usage:
preflight check container [flags]

Examples:
preflight check container quay.io/repo-name/container-name:version

Flags:
--certification-project-id string Certification Project ID from connect.redhat.com. Should be supplied without the ospid- prefix.
-d, --docker-config string path to docker config.json file
-h, --help help for container
--pyxis-api-token string API token for Pyxis authentication
--pyxis-host string Host to use for Pyxis submissions. (default "catalog.redhat.com/api/containers")
-s, --submit submit check container results to red hat

Global Flags:
-l, --list-checks lists all the checks run for a given check

FATA[0000] error calling remote API

Could you please have a look into it ?

Thanks,
Anil Dhaneshwar

**Comment by acornett21** [comment]
@anildhaneshwar The API ket needs to come from UAT as well. If the project and api key do not match you will get this error. I see the project exists in UAT, please make sure the key is from UAT as well. See the below URL to create a UAT api-key.

https://connect.uat.redhat.com/account/api-keys

**Comment by anildhaneshwar** [comment]
@acornett21 We are using same key but no luck. Let me know if you need any logs to debug it further.

Thanks,
Anil Dhaneshwar

**Comment by itroyano** [comment]
@anildhaneshwar what happens if instead of `PFLT_PYXIS_HOST=catalog.uat.redhat.com/api/containers`
you run the command with `--pyxis-host=catalog.uat.redhat.com/api/containers` ?

**Comment by anildhaneshwar** [comment]
We have followed the following steps for the preflight flight tool run:

Created a setup with required versions of OperatorSDK and OpenShift Client as mentioned [here](https://github.com/redhat-openshift-ecosystem/openshift-preflight/tree/e91e9dfece9ef5bed7f9ccedc1c4200b05fba305). Successfully created the preflight binary:
[root@sclswiftd630-37vm11 ~]# preflight --version
preflight version 0.0.0 <commit: e91e9dfece9ef5bed7f9ccedc1c4200b05fba305>

Project with the name: "InfoScale-SDS-test" is created under the Redhat UAT and Prod environments.

UAT: https://connect.uat.redhat.com/manage/projects
Prod: https://connect.redhat.com/manage/projects

Both environments are having same project name i.e. [InfoScale-SDS-test](https://connect.uat.redhat.com/projects/624aaedabe4dd77dc8638007/overview)

Tagged and pushed the image to Red Hat Container registry: InfoScale-SDS-test project under Prod environment: https://connect.redhat.com/manage/projects
Image is successfully submitted:


Executed the preflight tool using preflight binary (Step1) in the following format:

set $ PFLT_PYXIS_HOST=[catalog.uat.redhat.com/api/containers](http://catalog.uat.redhat.com/api/containers)

preflight check container registry.example.org/your-namespace/your-image:sometag \
--pyxis-api-token=<your-api-token> \
--certification-project-id=<cert-project-id>

Execution:
[root@sclswiftd630-37vm11 ~]# set $ PFLT_PYXIS_HOST=catalog.uat.redhat.com/api/containers
[root@sclswiftd630-37vm11 ~]# preflight check container [scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64](http://scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64) --pyxis-api-token=aczk97t7qq932c9ljq0bsly74ygk7yys --certification-project-id=624aaedabe4dd77dc8638007

Here: 
[ospid-6250064546dc0036e529344f](http://scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64) - project id of the prod project: "InfoScale-SDS-test", this project is having image uploaded.

[infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64](http://scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64) : Uploaded image name and tag
--pyxis-api-token=aczk97t7qq932c9ljq0bsly74ygk7yys : Token generated with name : "InfoScale-SDS-test" from UAT environment: https://connect.uat.redhat.com/account/api-keys
-certification-project-id=624aaedabe4dd77dc8638007 : project id of the UAT project : InfoScale-SDS-test. Have removed the ospid- prefix as mentioned below.(Under Flags section)

Received Following error:
time="2022-04-12T15:47:28+05:30" level=info msg="certification library version 0.0.0 <commit: e91e9dfece9ef5bed7f9ccedc1c4200b05fba305>"
time="2022-04-12T15:47:34+05:30" level=error msg="received non 200 status code in GetProject: {\"detail\": \"The server could not verify that you are authorized to access the URL requested. You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.\", \"status\": 401, \"title\": \"Unauthorized\", \"type\": \"about:blank\", \"trace_id\": \"0x3e09b3834b900527c67920848bd4befe\"}"
time="2022-04-12T15:47:34+05:30" level=error msg="error calling remote APIcould not retrieve project"
Error: error calling remote API
Usage:
  preflight check container [flags]
Examples:
  preflight check container [quay.io/repo-name/container-name:version](http://quay.io/repo-name/container-name:version)
Flags:
      --certification-project-id string   Certification Project ID from [conenct.redhat.com](http://conenct.redhat.com/). Should be supplied without the ospid- prefix.
  -d, --docker-config string              path to docker config.json file
  -h, --help                              help for container
      --pyxis-api-token string            API token for Pyxis authentication
      --pyxis-host string                 Host to use for Pyxis submissions. (default "[catalog.redhat.com/api/containers](http://catalog.redhat.com/api/containers)")
  -s, --submit                            submit check container results to red hat
Global Flags:
  -l, --list-checks   lists all the checks run for a given check
time="2022-04-12T15:47:34+05:30" level=fatal msg="error calling remote API"



Have tried this :

[root@sclswiftd630-37vm11 ~]# preflight check container [scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64](http://scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64) --pyxis-api-token=vohf61y1jtlxi8ml8lckx2rrycyza92j --certification-project-id=624aaedabe4dd77dc8638007 --pyxis-host=[catalog.uat.redhat.com/api/containers](http://catalog.uat.redhat.com/api/containers)

The error is changed as compared to the earlier one but we received the following error:

time="2022-04-12T14:33:34+05:30" level=info msg="certification library version 0.0.0 <commit: e91e9dfece9ef5bed7f9ccedc1c4200b05fba305>"
Error: failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-6250064546dc0036e529344f/infoscale Type:repository]]
time="2022-04-12T14:33:35+05:30" level=fatal msg="failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-6250064546dc0036e529344f/infoscale Type:repository]]"

**Comment by itroyano** [comment]
@anildhaneshwar the latest error is trying to pull the image to scan it.  can you provide `-d, --docker-config string path to docker config.json file` with the appropriate pull credentials ?

P.S:  is the image path correct?  I'm not sure if "opsid" should be there or not.

**Comment by anildhaneshwar** [comment]
@itroyano 

We tried your suggestion and passed the required docker flag, but still getting same error:

--- 
[root@dl360g10-117-con-v41 docker]# preflight check container scan.connect.redhat.com/ospid-6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64 --pyxis-api-token=79vkg9fpcrv48sahv6zig3p7ho1wh2xo --certification-project-id=624aaedabe4dd77dc8638007 --pyxis-host=catalog.uat.redhat.com/api/containers --docker-config=/etc/docker/daemon.json
time="2022-04-12T18:42:40+05:30" level=info msg="certification library version 0.0.0 <commit: e91e9dfece9ef5bed7f9ccedc1c4200b05fba305>"
Error: failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-6250064546dc0036e529344f/infoscale Type:repository]]
time="2022-04-12T18:42:44+05:30" level=fatal msg="failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-6250064546dc0036e529344f/infoscale Type:repository]]"
[root@dl360g10-117-con-v41 docker]# ls -l ~/snap/docker/current/.docker/
ls: cannot access '/root/snap/docker/current/.docker/': No such file or directory
[root@dl360g10-117-con-v41 docker]#

--- 

We have image in same project and built the path as per the doc.

Thanks,
Anil Dhaneshwar

**Comment by sumitkumarsoni** [comment]
Have tried the following steps as well:

1. Logged in to the prod project having an image that we need to scan:

[root@dl360g10-117-con-v41 docker]# docker login -u unused [scan.connect.redhat.com](http://scan.connect.redhat.com/)                                                  Password:

WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded

2. Ran the tool by passing this /root/.docker/config.json (having creds to login to the prod project) file as input to "--docker-config=" param, but received same error:
[root@dl360g10-117-con-v41 docker]# preflight check container [scan.connect.redhat.com/6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64](http://scan.connect.redhat.com/6250064546dc0036e529344f/infoscale:8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64) --pyxis-api-token=79vkg9fpcrv48sahv6zig3p7ho1wh2xo --certification-project-id=624aaedabe4dd77dc8638007 --pyxis-host=[catalog.uat.redhat.com/api/containers](http://catalog.uat.redhat.com/api/containers) --docker-config=/root/.docker/config.json

time="2022-04-12T19:24:51+05:30" level=info msg="certification library version 0.0.0 <commit: e91e9dfece9ef5bed7f9ccedc1c4200b05fba305>"
Error: failed to pull remote container: GET https://scan.connect.redhat.com/v2/6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:6250064546dc0036e529344f/infoscale Type:repository]]
time="2022-04-12T19:24:57+05:30" level=fatal msg="failed to pull remote container: GET https://scan.connect.redhat.com/v2/6250064546dc0036e529344f/infoscale/manifests/8.0.0.0000-rhel8.4-4.18.0-305.7.1.el8_4.x86_64: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:6250064546dc0036e529344f/infoscale Type:repository]]"



Do we need to have OperatorSDK and OpenShift Client installed on the system where we are running this tool? or OperatorSDK and OpenShift Client are just pre-requisites to build the "preflight" binary and preflight binary can be run on any RHEL system once built?

Thanks,
Sumit

**Comment by itroyano** [comment]
@tkrishtop @bcrochet @acornett21 shouldn't it be config.json instead of daemon.json,  after successfully logging into the repo?

**Comment by anildhaneshwar** [comment]
Thanks @itroyano @acornett21... Our issues are resolved now. Thanks for your help.
