### ISSUE TITLE
Required image labels may be carried over from base images

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#562]
## Bug Description
Preflight checks to ensure that a container image has required labels for submission to Certification. If the base image contains these labels, and the resulting image doesn't change them, the resulting image seems to have the base image's labels, which passes checks.

## Version and Command Invocation
All versions, `check container`. 

## Steps to Reproduce:
Build an image based on UBI, which has the required labels to pass the preflight label check. Here's an example Containerfile. 

```
FROM registry.access.redhat.com/ubi8/ubi-micro
USER 65532:65532

ENTRYPOINT ["/bin/sleep", "infinity"]
```

You can run `podman build -t preflight-label-test:no-labels -f Containerfile .` and then inspect the resulting image's labels.

```
podman  image inspect preflight-label-test:no-labels \
  | jq '.[].Config.Labels \
  | .name, .vendor, .version, .release, .summary, .description' 
```

It reflects the UBI's labels

```
$ podman  image inspect preflight-label-test:no-labels \
  | jq '.[].Config.Labels \
  | .name, .vendor, .version, .release, .summary, .description' 
"ubi8/ubi-micro"
"Red Hat, Inc."
"8.5"
"833"
"ubi8 micro image"
"Very small image which doesn't install the package manager."
```

## Additional Context
For the most part... this seems like expected behavior. It's entirely possible that this may be a "WONTFIX" scenario due to the potentially difficulty of reliably identifying base image labels, and differentiating between what is basically a freeform string value from what's coming from the base image.

That said, I wanted to report the issue to see if there are creatives ways to ensure that an image isn't being submitted missing these labels as I believe they help inform things on the Connect side (metadata to consumers).

**Comment by acornett21** [comment]
We should probably do what CVP does and make a call to pyxis for this unfortunately :(

```
List<Map> getImageLabels(String pyxisContainerimageId) {
    Map repoQuery = [query    : '''
                        query($imageId: ID!) {
                          get_image(id: $imageId) {
                            error {
                              status
                              detail
                            }
                            data {
                              _id
                              brew {
                                build
                                nvra
                                package
                                completion_date
                              }
                              parsed_data {
                                labels {
                                  name
                                  value
                                }
                              }
                            }
                          }
                        }''',
                     variables: [imageId: pyxisContainerimageId]
    ]```

and then make sure they are not inherited.

**Comment by komish** [comment]
Closing this as stale.
