### ISSUE TITLE
BasedOnUbi check fails with Error when querying pyxis for uncompressed top layer idsMessage: Unexpected error occurred, Locations: []

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#570]
## Bug Description
BasedOnUbi check fails with Error when querying pyxis for uncompressed top layer idsMessage: Unexpected error occurred, Locations: []
## Version and Command Invocation
preflight version 0.0.0 <commit: 47ea7c93db9fb2aa8aad097ce85c2d7f123c22ad>

## Steps to Reproduce:
(How can we reproduce this?)
1) Run preflight check container with submit
2)
3)

## Expected Result
BasedOnUbi check should pass 

## Actual Result
http://pastebin.test.redhat.com/1045379
`time="2022-04-18T07:40:11Z" level=debug msg="running check: RunAsNonRoot"
time="2022-04-18T07:40:11Z" level=info msg="USER preflightuser specified that is non-root"
time="2022-04-18T07:40:11Z" level=info msg="check completed: RunAsNonRoot" result=PASSED
time="2022-04-18T07:40:11Z" level=debug msg="running check: BasedOnUbi"
time="2022-04-18T07:40:17Z" level=error msg="could not marshal GraphQL query: Message: Unexpected error occurred, Locations: []"
time="2022-04-18T07:40:17Z" level=error msg="Error when querying pyxis for uncompressed top layer idsMessage: Unexpected error occurred, Locations: []"
time="2022-04-18T07:40:17Z" level=error msg="Unable to verify layer hashesMessage: Unexpected error occurred, Locations: []"
time="2022-04-18T07:40:17Z" level=info msg="check completed: BasedOnUbi" ERROR="Message: Unexpected error occurred, Locations: []" result="Message: Unexpected error occurred, Locations: []"
time="2022-04-18T07:40:17Z" level=debug msg="running check: HasModifiedFiles"`

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by acornett21** [comment]
I believe there is still an outage with pyxis based on what I see in servicenow.

**Comment by bcrochet** [comment]
Cam be tracked here: https://issues.redhat.com/browse/CLOUDWF-7488
