### ISSUE TITLE
Enable Test Code Coverage Reporting

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/openshift-preflight#573]
## Is your feature request related to a problem? Please describe.

We have been asked to report on the test code coverage for preflight.

## Describe the solution you'd like.

Ginko has a flag for this, so hopefully we can add that to the `test` target in our Makefile.

## Describe alternatives you've considered.

N/A

## Additional context.

We have the unit test output saved as part of the GitHub build action when something is merged into main, so I think this should suffice for now to have the coverage outputted as part of the `test` target.

**Comment by acornett21** [comment]
I like the idea of this as a starting point, maybe not needed right now, but maybe we also do something similar to [this](https://itnext.io/github-actions-code-coverage-without-third-parties-f1299747064d)? ie

- Test coverage on PR and block under a certain % (maybe not useful today, but future state)
- Add the coverage to our readme else where in GH.

**Comment by jomkz** [comment]
I am fine with that approach and I like the idea of blocking a PR if the test coverage does not meed a certain threshold.

**Comment by bcrochet** [comment]
At least there needs to be a positive delta, not necessarily a specific percentage.

**Comment by acornett21** [comment]
> At least there needs to be a positive delta, not necessarily a specific percentage.

I agree this is ideally the way to go, not sure if any of the tools work like this though. I've never seen one setup this way, it's always a `>85%` type situation. The 2nd link is probably more along the lines of what we were talking about in the meeting. Shows the coverage by packages in the comments of a PR.

**Comment by komish** [comment]
Initial coverage:

```08:56:49 ~/.go/src/github.com/redhat-openshift-ecosystem/openshift-preflight
$ go tool cover -func coverage.out | grep total: | column -t
total:  (statements)  36.9%```

**Comment by acornett21** [comment]
Relates: #667
