### ISSUE TITLE
[Multiarch]Preflight fails with panic: runtime error: invalid memory address or nil pointer dereference for rpm-manifest for rhel9 images

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#578]
## Bug Description
[Power9]Preflight fails with panic: runtime error: invalid memory address or nil pointer dereference for rpm-manifest
## Version and Command Invocation
preflight version 1.1.0-rc1 <commit: 0c0918de527faae53b5df9efb7a054af533d455c>

## Steps to Reproduce:
(How can we reproduce this?)
1) ./preflight-linux-ppc64le check container registry.access.redhat.com/rhel9-beta/support-tool:9.0.0beta-3
2)
3)

## Expected Result
Preflight should run the tests

## Actual Result
`[root@rdma-cert-03-lp7 ~]# ./preflight-linux-ppc64le check container registry.access.redhat.com/rhel9-beta/support-tools:9.0.0beta-3
time="2022-04-21T03:52:53-04:00" level=debug msg="config file not found, proceeding without it"
time="2022-04-21T03:52:53-04:00" level=info msg="certification library version 1.1.0-rc1 <commit: 0c0918de527faae53b5df9efb7a054af533d455c>"
time="2022-04-21T03:52:53-04:00" level=debug msg="target image: registry.access.redhat.com/rhel9-beta/support-tools:9.0.0beta-3"
time="2022-04-21T03:52:53-04:00" level=debug msg="pulling image from target registry"
time="2022-04-21T03:52:53-04:00" level=debug msg="temporary directory is /tmp/preflight-28931403"
time="2022-04-21T03:52:53-04:00" level=debug msg="exporting and flattening image"
time="2022-04-21T03:52:53-04:00" level=debug msg="extracting container filesystem to /tmp/preflight-28931403/fs"
time="2022-04-21T03:52:53-04:00" level=debug msg="writing container filesystem to output dir: /tmp/preflight-28931403/fs"
time="2022-04-21T03:53:06-04:00" level=trace msg="image config written to disk: /root/artifacts/cert-image.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47e9fc]

goroutine 73 [running]:
database/sql.(*Rows).Next(0x0)
	/opt/hostedtoolcache/go/1.17.8/x64/src/database/sql/sql.go:2944 +0x2c
github.com/knqyf263/go-rpmdb/pkg/sqlite3.(*SQLite3).Read.func1(0xc00013e0c0, 0xc0004703b0)
	/home/runner/go/pkg/mod/github.com/opdev/go-rpmdb@v0.0.0-20220329221310-ca9c80a97804/pkg/sqlite3/sqlite3.go:67 +0x240
created by github.com/knqyf263/go-rpmdb/pkg/sqlite3.(*SQLite3).Read
	/home/runner/go/pkg/mod/github.com/opdev/go-rpmdb@v0.0.0-20220329221310-ca9c80a97804/pkg/sqlite3/sqlite3.go:52 +0x5c`

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by itroyano** [comment]
@vikasmulaje can you open a shell into the image and verify the rpm db is there?

@bcrochet @acornett21 Is there an actual use case where https://catalog.redhat.com/software/containers/rhel9-beta/support-tools/60a9fcacaf9de74bd5388048 is used as a base image for a product being certified?
based on the description, this looks like a standalone runnable toolkit.
not something that a partner or a customer may try to certify with Preflight...

**Comment by vikasmulaje** [comment]
@itroyano This works in amd64 but in power machine it fails

**Comment by itroyano** [comment]
@bcrochet line seems to be https://github.com/opdev/go-rpmdb/blob/master/pkg/sqlite3/sqlite3.go#L67
and this piece of code matches upstream.
I'm not entirely sure how a seg fault or an index out of bounds type error can occur here, since https://pkg.go.dev/database/sql#Rows.Next does a check if there is a "next"...
and more importantly - why it doesn't happen on amd64.

**Comment by itroyano** [comment]
UPDATE from @vikasmulaje  - Preflight runs successfully as an image w `podman run`.
 the error happens with the binary.

**Comment by bcrochet** [comment]
We need to verify that the image under test is actually a power image. Perhaps an arch mismatch causes this?

**Comment by vikasmulaje** [comment]
@bcrochet I verified the images they are power images. 

`[root@rdma-cert-03-lp7 ~]# podman inspect a2081dd535e1983966feab0e3ac13f23bda88e2b47eea7b623e61895c0e31e95
[
    {
        "Id": "a2081dd535e1983966feab0e3ac13f23bda88e2b47eea7b623e61895c0e31e95",
        "Digest": "sha256:5ecf1aadc8be1bb10e061d1f839057982503f3956911ca1c428fdacac255e9be",
        "RepoTags": [
            "registry.access.redhat.com/rhel9-beta/support-tools:9.0.0beta-3"
        ],
        "RepoDigests": [
            "registry.access.redhat.com/rhel9-beta/support-tools@sha256:5ecf1aadc8be1bb10e061d1f839057982503f3956911ca1c428fdacac255e9be",
            "registry.access.redhat.com/rhel9-beta/support-tools@sha256:7ae46a847658febea5152c9299e6d87e260307f457f36cff66e7e92344aa9a5e"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-10-13T14:19:25.132029Z",
        "Config": {
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "container=oci"
            ],
            "Cmd": [
                "/usr/bin/bash"
            ],
            "Labels": {
                "architecture": "ppc64le",
                "build-date": "2021-10-13T14:18:13.744404",
                "com.redhat.build-host": "ppc64le-c3-vm-11.osbs.prod.psi.rdu2.redhat.com",
                "com.redhat.component": "support-tools-container",
                "com.redhat.license_terms": "https://www.redhat.com/agreements",
                "description": "The Red Hat Enterprise Linux Support Tools image contains tools to analyze the host system including sos, tcpdump, strace, and more.",
                "distribution-scope": "public",
                "io.k8s.description": "The Red Hat Enterprise Linux Support Tools image contains tools to analyze the host system including sos, tcpdump, strace, and more.",
                "io.k8s.display-name": "Red Hat Enterprise Linux Support Tools",
                "io.openshift.expose-services": "",
                "io.openshift.tags": "sos, soscleaner, sos-collector, sosreport, support, diag",
                "maintainer": "Red Hat, Inc.",
                "name": "rhel9/support-tools",
                "release": "3",
                "run": "podman run -it --name NAME --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=NAME -e IMAGE=IMAGE -v /run:/run -v /var/log:/var/log -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -v /:/host IMAGE",
                "summary": "A set of tools to analyze the host system.",
                "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/rhel9/support-tools/images/9.0.0beta-3",
                "usage": "podman container runlabel RUN rhel9/support-tools",
                "vcs-ref": "dd10b8d9ddaec25f63d1dca3862262be14a157ff",
                "vcs-type": "git",
                "vendor": "Red Hat, Inc.",
                "version": "9.0.0beta"
            }
        },
        "Version": "1.13.1",
        "Author": "",
        "Architecture": "ppc64le",
        "Os": "linux",
        "Size": 306296815,
        "VirtualSize": 306296815,
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/containers/storage/overlay/8cadaf0c74dd0cc79cc8f43275268c6bb34f5a9821b893454867879fa7ed46be/diff:/var/lib/containers/storage/overlay/8710ceee6ff0f18194cf2dedc88000bc0ff74d5741d40aeee6d793a5cb23d884/diff",
                "UpperDir": "/var/lib/containers/storage/overlay/1df445425e06f9a65f80a2ed35d6697b7e931022617c665c0d134b92221ce192/diff",
                "WorkDir": "/var/lib/containers/storage/overlay/1df445425e06f9a65f80a2ed35d6697b7e931022617c665c0d134b92221ce192/work"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:8710ceee6ff0f18194cf2dedc88000bc0ff74d5741d40aeee6d793a5cb23d884",
                "sha256:8ac92c3475864e4a7ea18e12cdea2f66e04114f5fcc792525ac9c269ab72035c",
                "sha256:2311edbf8c6a5bc7728b8146f0112adc9c10753ba1702d6d59313c0da9dc3fdd"
            ]
        },
        "Labels": {
            "architecture": "ppc64le",
            "build-date": "2021-10-13T14:18:13.744404",
            "com.redhat.build-host": "ppc64le-c3-vm-11.osbs.prod.psi.rdu2.redhat.com",
            "com.redhat.component": "support-tools-container",
            "com.redhat.license_terms": "https://www.redhat.com/agreements",
            "description": "The Red Hat Enterprise Linux Support Tools image contains tools to analyze the host system including sos, tcpdump, strace, and more.",
            "distribution-scope": "public",
            "io.k8s.description": "The Red Hat Enterprise Linux Support Tools image contains tools to analyze the host system including sos, tcpdump, strace, and more.",
            "io.k8s.display-name": "Red Hat Enterprise Linux Support Tools",
            "io.openshift.expose-services": "",
            "io.openshift.tags": "sos, soscleaner, sos-collector, sosreport, support, diag",
            "maintainer": "Red Hat, Inc.",
            "name": "rhel9/support-tools",
            "release": "3",
            "run": "podman run -it --name NAME --privileged --ipc=host --net=host --pid=host -e HOST=/host -e NAME=NAME -e IMAGE=IMAGE -v /run:/run -v /var/log:/var/log -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -v /:/host IMAGE",
            "summary": "A set of tools to analyze the host system.",
            "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/rhel9/support-tools/images/9.0.0beta-3",
            "usage": "podman container runlabel RUN rhel9/support-tools",
            "vcs-ref": "dd10b8d9ddaec25f63d1dca3862262be14a157ff",
            "vcs-type": "git",
            "vendor": "Red Hat, Inc.",
            "version": "9.0.0beta"
        },
        "Annotations": {},
        "ManifestType": "application/vnd.docker.distribution.manifest.v2+json",
        "User": "",
        "History": [
            {
                "created": "2021-10-12T10:52:35.832232068Z",
                "comment": "Imported from -"
            },
            {
                "created": "2021-10-12T10:53:08.536754Z"
            },
            {
                "created": "2021-10-13T14:19:25.132029Z"
            }
        ],
        "NamesHistory": [
            "registry.access.redhat.com/rhel9-beta/support-tools:9.0.0beta-3"
        ]
    }
]`

**Comment by acornett21** [comment]
From my testing something weird is going on either with the registry or with `crane`. If you test the rhel9 support tools image by tag you get the `amd64` image written to disk. But if you pull by the `ppc64le` sha the architecture written to disk is correct, however the same error is still throw. Need to test more, but this are my initial findings.

**Comment by acornett21** [comment]
After looking at this more it looks like our build process of the binaries (the binary in our containers work correctly) is not `CGO_ENABLED` properly. The sqlite library we use requires `CGO_ENABLED=1` this is why REHL9 images fail. This issue also affects `s390x` systems.

**Comment by vikasmulaje** [comment]
@acornett21 FYI, This also affects arm64.

**Comment by acornett21** [comment]
> FYI, This also affects arm64.

@vikasmulaje On `arm64` it's just the binary correct? The container runs properly?

**Comment by vikasmulaje** [comment]
Yes, its only the binary in releases, container works fine.
