### ISSUE TITLE
test "RunAsNonRoot" is failing for project

### ISSUE THREAD

**Issue by anildhaneshwar** [redhat-openshift-ecosystem/openshift-preflight#585]
Hi,

We have a project: "InfoScale SDS" with Project ID: ospid-617a96d3bcb1628c8d251dd6 on the Redhat registry. While running the preflight tool, the test "RunAsNonRoot" is failing for this project.
This project needs to run as a root user only and we can't allow access to the non-root user for this project. We request to allow an exception for the test "RunAsNonRoot" for this project.

Thanks,
Anil Dhaneshwar

**Comment by vikasmulaje** [comment]
Hi Anil,

For running container as root and to skip "RunAsNonRoot" check you need to set the Privileged checkbox in https://connect..redhat.com/projects/617a96d3bcb1628c8d251dd6/settings and rerun the tests.

Thanks

**Comment by anildhaneshwar** [comment]
@vikasmulaje, Thanks for response ! 

The shared link is not working. Could you please check ?

**Comment by anildhaneshwar** [comment]
@vikasmulaje Thanks for response !
