### ISSUE TITLE
Identify and build quay namespace for test container and operator assets

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#59]
When we decide to build and enable e2e tests, we will need to have test assets available in a publicly accessible location so that we can run those tests against known-good and known-bad assets.

The Quay namespace where this will be hosted needs to be identified so that we can start looking at automated build and publication of those assets.

**Comment by bcrochet** [comment]
Any reason not to just start with opdev, and move if necessary?

**Comment by komish** [comment]
@bcrochet Nope, that works for me. I'll move them now, and maybe get the automation hooked up so that they publish frequently. 

I had initially created this issue before we started uploading preflight to opdev. Now that that's done, might as well put everything there.

I'll work on this.

/assign

**Comment by jomkz** [comment]
@bcrochet I am going through and cleaning up old issues Can you confirm that we can close this now? I believe that we have everything that we need in place already.

**Comment by bcrochet** [comment]
I'm ok with closing this.
