### ISSUE TITLE
running preflight check container as root fails (RHEL 8.5)

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/openshift-preflight#597]
## Bug Description
`preflight check container` fails when run as root on a reagainst scan.connect.redhat.com, even with correct remote credentials.

## Version and Command Invocation
`preflight version 1.1.0 <commit: f1628fcf489aed88711d6cac95c3f096217f9feb>`

`preflight check container scan.connect.redhat.com/ospid-61dc8f24e4578f8bf95ed986/fake-product:1.0 --pyxis-api-token=fyimy77nix6dtelac7zzanycy1g1ttac --certification-project-id=61dc8f24e4578f8bf95ed986`

## Steps to Reproduce:
(How can we reproduce this?)
1) Become root on a RHEL 8 box.
2) Log in to a specific registry on scan.connect.redhat.com using a registry key.
3) Run the Preflight scan against a container there.

## Expected Result
Correct scanning behavior, as happens when running as an ordinary user

```
ryzen1> whoami
jfrancin
ryzen1> preflight check container scan.connect.redhat.com/ospid-61dc8f24e4578f8bf95ed986/fake-product:1.0 --pyxis-api-token=fyimy77nix6dtelac7zzanycy1g1ttac --certification-project-id=61dc8f24e4578f8bf95ed986
time="2022-05-02T19:55:24-04:00" level=info msg="certification library version 1.1.0 <commit: f1628fcf489aed88711d6cac95c3f096217f9feb>"
time="2022-05-02T19:57:22-04:00" level=info msg="check completed: HasModifiedFiles" result=PASSED
time="2022-05-02T19:57:22-04:00" level=error msg="Error when checking for /licenses : stat /tmp/preflight-610532146/fs/licenses: no such file or directory"
time="2022-05-02T19:57:22-04:00" level=info msg="check completed: HasLicense" result=FAILED
time="2022-05-02T19:57:22-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
[...]

```
## Actual Result
Failure:

```
[root@ryzen1 ~]# ~jfrancin/bin/preflight check container scan.connect.redhat.com/ospid-61dc8f24e4578f8bf95ed986/fake-product:1.0 --pyxis-api-token=fyimy77nix6dtelac7zzanycy1g1ttac --certification-project-id=61dc8f24e4578f8bf95ed986
time="2022-05-02T19:58:40-04:00" level=info msg="certification library version 1.1.0 <commit: f1628fcf489aed88711d6cac95c3f096217f9feb>"
Error: failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-61dc8f24e4578f8bf95ed986/fake-product/manifests/1.0: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-61dc8f24e4578f8bf95ed986/fake-product Type:repository]]
time="2022-05-02T19:58:47-04:00" level=fatal msg="failed to pull remote container: GET https://scan.connect.redhat.com/v2/ospid-61dc8f24e4578f8bf95ed986/fake-product/manifests/1.0: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:ospid-61dc8f24e4578f8bf95ed986/fake-product Type:repository]]"
```

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

Platform: 
```
ryzen1> uname -a
Linux ryzen1.narfnet.com 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bcrochet** [comment]
My guess at this point is that a different docker config was being used. Can you attempt this with the latest version of preflight (1.1.1), and pass --docker-config <full path to a dockerconfig.json> or set PFLT_DOCKERCONFIG.

**Comment by acornett21** [comment]
I believe this is now fixed, since a partner was using an older version on RHEL and `root` and preflight was failing. They got the latest version and were able to submit their image(s). Going to close this issue. If it's still an issue for other partners, please feel free to re-open.
