### ISSUE TITLE
Implement `certify` subcommand to submit results for certification

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#61]
The preflight tool should allow a user to take their results on-disk and submit them to Red Hat for review. The API endpoint is TBD.

**Comment by komish** [comment]
This is already stubbed as the `certify` subcommand. It is not implemented yet as we're awaiting API contract definition as mentioned previously.

**Comment by jomkz** [comment]
This should be covered by #369

**Comment by jomkz** [comment]
Closing this issue, as the `certify` sub command will be removed in favore of a flag passed to `check container`.
