### ISSUE TITLE
Configure Github actions to publish preflight-darwin-amd64 binaries.

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#632]
I don't see MacOS binaries, and it would be useful to have them also versioned to make it easier to test for bugs.

**Comment by acornett21** [comment]
I thought we were only `supporting rhel`, but I do see this useful since partners on macs are already taking our releases and compiling the source. Also, if/when the `version check` aka auditing goes into place, us having more binaries available would be helpful.

**Comment by komish** [comment]
Gotcha. I thought we used to have them, but I was probably just constantly running `make build` in those days so I had all recent version. I'm all good here.

/close
