### ISSUE TITLE
Add unit tests for checks HasLicense, HasNoProhibitedPackages, RunAsNonRoot

### ISSUE THREAD

**Issue by edreyer-1** [redhat-openshift-ecosystem/openshift-preflight#64]
Add unit tests for the the checks that use podman run. This include checks HasLicense, HasNoProhibitedPackages, and RunAsNonRoot.

**Comment by komish** [comment]
@edreyer-1 are you working on this? No problem if not, just want to make sure it's assigned to you if you are!

**Comment by edreyer-1** [comment]
Yes I was about to put up a pull request for it but I couldn't figure out how to assign it to myself.
