### ISSUE TITLE
Add a Preflight command that disables submission entirely in favor of more developer flexibility as to what actually runs.

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#647]
### Problems

- A specific example would be to allow users to specify exactly which checks they want executed as a part of their run.

- Today, users cannot tell preflight exactly which checks they want to run. This can be advantageous, however, if they want to shorten the feedback cycle (think, “I don’t want to run DeployableByOLM” because I’m offline right now on the train hacking on my operator).

### The solution should:

- Wire up a subcommand that gives the developer more flexibility on what checks preflight runs per policy without impacting any existing workflows, or allowing the developer to submit partial results.

**Comment by tkrishtop** [comment]
@komish having offline-friendly pipeline runs is a great idea! Some partners with isolated offline environments would be happy - right now they can't run preflight.

**Comment by komish** [comment]
Closing this issue as stale as there are no plans to implement this specific behavior. There are more specific issues that intend to help more offline-centric workflows consume preflight. Ref: https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/781.

If this feature as described in this issue is relevant to you, feel free to re-open. Otherwise, feel free to open a new issue.
