### ISSUE TITLE
The current check_url path for HasRequiredLabel doesn't lead to what's required for the container check

### ISSUE THREAD

**Issue by rocrisp** [redhat-openshift-ecosystem/openshift-preflight#648]
## Bug Description
For Preflight container check, I got an error for HasRequiredLabel.
check_url path says to go "https://access.redhat.com/documentation/en-us/red_hat_openshift_certification/4.9/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction"
I was expecting an answer instead I got the "Product Documentation For Red Hat Software Certification 8.45"

## Version and Command Invocation
I built preflight using Vagrantfile hence the version 0.0.0.
preflight version 0.0.0 <commit: e96c75f8b0c7d75d6e6298219fc96f7dcaa38f9f>

## Steps to Reproduce:
(How can we reproduce this?)
1)preflight/preflight check container quay.io/opdev/l5-operator:v0.0.2

## Expected Result
(What did you expect to happen and why?)
I expect to see the check_url path:
https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.45/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction#con-image-metadata-requirements_openshift-sw-cert-policy-container-images

## Actual Result
(What actually happened)
check_url path for HasRequiredLabel
https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.45#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

**Comment by rocrisp** [comment]
We might as well update the check_url for the following container check :
BasedOnUbi, HasLicense.
Also update knowledgebase_url for the container checks.

**Comment by acornett21** [comment]
I forgot they moved the documetation and no longer do a re-direct. We should update the new URL should be
`certDocumentationURL= "https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.45/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction"` in `defaults.go`

I wish they had specific anchors that we could use in each check, but they do not. :(

**Comment by jomkz** [comment]
See the comment from Kelly on the following issue for the work being done to the certification docs.

https://issues.redhat.com/browse/PEC-288

The way that I read her comment, if we keep using the URL with the certification version number, anchors may work for us if we can get them added.

**Comment by acornett21** [comment]
If they add anchors, that would make `preflights` output alot better for our users.
