### ISSUE TITLE
preflight check container error msg="could not retrieve project: invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by Bhagyashreek8** [redhat-openshift-ecosystem/openshift-preflight#653]
## Bug Description
(A clear and concise description of the issue)
preflight check container command on linux returns `time="2022-05-20T17:06:57Z" level=error msg="could not retrieve project: invalid character '<' looking for beginning of value"` where as the same preflight command works on macos.

## Version and Command Invocation
(The output of `preflight --version`)

`preflight version 0.0.0 <commit: 95e34349190790283d340f0ac2407b0cfb66a096>`

############# push driver image to redhat repo ########
```preflight check container cp.icr.io/cpopen/ibmcloud-object-storage-driver:1.8.46 --submit --pyxis-api-token=$redhat_pyxis_token --certification-project-id=5eba51af0537cdbd17e451e9 --docker-config=/home/travis/config.json```

The config.json file is as below -
```
{
	"auths": {
		"cp.icr.io": {
			"auth": "xxxxxxxxxxxxxx"
		}
	}
}
```

Error recieved -
```
time="2022-05-20T17:06:57Z" level=debug msg="config file not found, proceeding without it"

time="2022-05-20T17:06:57Z" level=info msg="certification library version 0.0.0 <commit: 95e34349190790283d340f0ac2407b0cfb66a096>"

time="2022-05-20T17:06:57Z" level=debug msg="URL is: https://catalog.redhat.com/api/container/v1/projects/certification/id/5eba51af0537cdbd17e451e9"

time="2022-05-20T17:06:57Z" level=error msg="invalid character '<' looking for beginning of value"

time="2022-05-20T17:06:57Z" level=error msg="could not retrieve project: invalid character '<' looking for beginning of value"

Error: invalid character '<' looking for beginning of value

Usage:

  preflight check container [flags]

Examples:

  preflight check container quay.io/repo-name/container-name:version

Flags:

      --certification-project-id string   Certification Project ID from connect.redhat.com/projects/{certification-project-id}/overview

                                          URL paramater. This value may differ from the PID on the overview page. (env: PFLT_CERTIFICATION_PROJECT_ID)

  -h, --help                              help for container

      --pyxis-api-token string            API token for Pyxis authentication (env: PFLT_PYXIS_API_TOKEN)

      --pyxis-env string                  Env to use for Pyxis submissions. (default "prod")

      --pyxis-host string                 Host to use for Pyxis submissions. This will override Pyxis Env. Only set this if you know what you are doing.

                                          If you do set it, it should include just the host, and the URI path. (env: PFLT_PYXIS_HOST)

  -s, --submit                            submit check container results to red hat

Global Flags:

  -d, --docker-config string   Path to docker config.json file. This value is optional for publicly accessible images.

                               However, it is strongly encouraged for public Docker Hub images,

                               due to the rate limit imposed for unauthenticated requests. (env: PFLT_DOCKERCONFIG)

  -l, --list-checks            lists all the checks run for a given check

time="2022-05-20T17:06:57Z" level=fatal msg="invalid character '<' looking for beginning of value"
```

## Steps to Reproduce:
(How can we reproduce this?)
1) Install all the pre-reqs for preflight and then install preflight from source - In linux environment
```
git clone https://github.com/redhat-openshift-ecosystem/openshift-preflight.git
cd openshift-preflight/
make build
chmod +x preflight
sudo mv preflight /usr/local/bin/
```
2) Set the env vars
```
export PFLT_LOGLEVEL=debug
export PFLT_LOGFILE=preflight.log
export PFLT_ARTIFACTS=artifacts/
export PFLT_PYXIS_HOST=catalog.redhat.com/api/container
```
3) Run preflight check container command against the image `cp.icr.io/cpopen/ibmcloud-object-storage-driver:1.8.46`

## Expected Result
(What did you expect to happen and why?)
Expected the image get scanned and pushed to redhat repo.

## Actual Result
(What actually happened)
1. Image scan locally works - `preflight check container $PFLT_DRIVER_INDEXIMAGE`
2. preflight check container with --submit works on macos.
3. The same preflight check container which worked on mac throws above error in linux environment

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).
From the error it seems it is expecting a json file whereas it is getting html or other file from api response.

Also this error is from the travis automation which run on unbuntu os.
```
Operating System Details

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

git version
git version 2.35.0

bash version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
```

**Comment by jomkz** [comment]
@Bhagyashreek8 please check the value you are using for ``. This should be `catalog.redhat.com/api/containers` (note the 's' on the end of the path. Also, that is the default so it *should* not be needed.

**Comment by bcrochet** [comment]
Usage of PFLT_PYXIS_HOST is **highly** discouraged. If you are just going against prod, it is not necessary to specify it at all.

**Comment by Bhagyashreek8** [comment]
Yes fixing the `PFLT_PYXIS_HOST` resolved my issue. 
Thank you.
