### ISSUE TITLE
Implement a new operator check to verify that all CSV images are certified

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/openshift-preflight#684]
## Is your feature request related to a problem? Please describe.

We need to implement a new operator check that will inspect the CSV for a given operator and verify that all images referenced are certified.

## Describe the solution you'd like.

Can we use the public Pyxis API to query for the certified status for every image listed in the CSV for a given operator?

## Describe alternatives you've considered.

We also need to investigate the level of effort to require that all images used by an operator are also listed in the `relatedImages` section of the CSV.

## Additional context.

Currently the helm certification does this, so perhaps we could borrow from the [chart-verifier](https://github.com/redhat-certification/chart-verifier)?

**Comment by acornett21** [comment]
closing this duplicate
