### ISSUE TITLE
[Container cert] Need a better way to handle public repos

### ISSUE THREAD

**Issue by jfrancin** [redhat-openshift-ecosystem/openshift-preflight#693]
## Is your feature request related to a problem? Please describe.

Partners who are using public repos (i.e., repos that don't require authentication) are coming up with many, um, creative ways of dealing with this fact.  Usually it involves leaving off the --docker-config option.  Sometimes it involves using a docker-config.json file for another, different registry - which works for the local scan (why?) but later causes Clair to fail because of the incorrect registry.

The only approach that really works is to provide a null authentication stanza, such as:

```
{
    "auths": {
        "quay.io": {
            "auth": ""
        }
    }
}

```

This is awkward and unintuitive; we've had to give this remedy to several partners in the past couple of weeks.

## Describe the solution you'd like.

Add a `--public` option which, if provided, causes Preflight to create a null authentication JSON stanza like the above (to pass to Pyxis), and also satisfies the --docker-config=<json-file-spec> requirement. 

## Describe alternatives you've considered.
(A clear and concise description of any alternative solutions or features you've considered.)

## Additional context.
(Add any other context or screenshots about the feature request here.)

**Comment by acornett21** [comment]
I think this will be fixed by our approach in #685.

**Comment by acornett21** [comment]
I also think that there needs to be enhancements to the clair wrapper to work like a normal container tool, ie podman, docker, crane, etc and only use auth when auth is needed, not when a repo is public. It's strange all the missmatches that are happening, I feel like they are re-inventing the wheel.

**Comment by komish** [comment]
I believe this issue can be closed given that the referenced issue, and associated PR addresses cases where a user has not passed in a docker config json, whereby preflight skips inclusion of that value in the submission. Please re-open if this is not resolved!
