### ISSUE TITLE
Authentication to docker.io appears to be broken

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#731]
## Bug Description
Trying to pull private images from docker.io appears to be broken, even with valid credentials.

## Version and Command Invocation, steps to reproduce
(Reproduce) Create a valid docker credential file and pass it to preflight to pull a private image.

```
$ PFLT_LOGLEVEL=trace ./preflight check container docker.io/xkomish/sleeper-test:latest --docker-config ./auth.json 
time="2022-07-18T09:55:06-05:00" level=debug msg="config file not found, proceeding without it"
time="2022-07-18T09:55:06-05:00" level=info msg="certification library version 0.0.0 <commit: 4ae2b40b01d3376d443d7a351c77f08a0fdf4cf0>"
time="2022-07-18T09:55:06-05:00" level=debug msg="target image: docker.io/xkomish/sleeper-test:latest"
time="2022-07-18T09:55:06-05:00" level=debug msg="pulling image from target registry"
time="2022-07-18T09:55:06-05:00" level=trace msg="entering preflight keychain Resolve"
Error: failed to pull remote container: GET https://index.docker.io/v2/xkomish/sleeper-test/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:xkomish/sleeper-test Type:repository]]
time="2022-07-18T09:55:07-05:00" level=fatal msg="failed to pull remote container: GET https://index.docker.io/v2/xkomish/sleeper-test/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:xkomish/sleeper-test Type:repository]]"
```

The same creds with podman appear to work

```
$ podman pull --authfile ./auth.json docker.io/xkomish/sleeper-test:latest
Trying to pull docker.io/xkomish/sleeper-test:latest...
Getting image source signatures
Copying blob sha256:bdbbaa22dec6b7fe23106d2c1b1f43d9598cd8fc33706cc27c1d938ecd5bffc7
Copying blob sha256:bdbbaa22dec6b7fe23106d2c1b1f43d9598cd8fc33706cc27c1d938ecd5bffc7
Copying config sha256:4d24b97186c7a265c78aebe5d356cb108aefad9648eb36608d11530b39ac64a3
Writing manifest to image destination
Storing signatures
4d24b97186c7a265c78aebe5d356cb108aefad9648eb36608d11530b39ac64a3
```

## Expected Result
Preflight should be able to authenticate to docker.io using the provided credentials.

## Actual Result
It's unauthorized.

**Comment by komish** [comment]
Temporarily, the workaround to run Preflight successfully against images hosted in Docker's container registry is to use the `https://index.docker.io/v1/` endpoint in your `$DOCKER_CONFIG/config.json` for your image. This is what's written by both dockercli and crane when authenticating to the registry.

**Comment by komish** [comment]
@lslebodn +1, we don't want to special case here, and noted the previous workaround to unblock folks for the moment.

The problem is that preflight internals (crane) fail to associate `docker.io*` as a valid auth endpoint for the docker hub. Docker CLI also fails to recognize it in my testing. That makes podman (and related libs) the only tool that seems to parse `docker.io*` properly.

The current proposed solution is to rewrite docker.io entries for internal use so that users don't feel the change. Alternatively, we need to also implement a workaround for submissions to Red Hat, which I believe (need confirmation) does not tie `https://index.docker.io/v1/` as the appropriate credentials for an image with the hostname `docker.io`.

**Comment by lslebodn** [comment]
> The current proposed solution is to rewrite docker.io entries

Such simple modification after reading json file should work as well.
It is just my preference to report issues with input data. Either as _error_ or maybe just a _warning_ in this case.
Rather than fixing them for user.

If you decide to fix it would be trivial  as well :-)
Pseudo-code:
```
docker_config_json = load_json_as_map("run/user/0/containers/auth.json")
if "docker.io" in docker_config_json["auths"].keys() and "https://index.docker.io/v1/" not in docker_config_json["auths"].keys()
    docker_config_json["auths"]["https://index.docker.io/v1/"]  = docker_config_json["auths"]["docker.io"]
```
