### ISSUE TITLE
preflight just fails on container image test

### ISSUE THREAD

**Issue by imperialguy** [redhat-openshift-ecosystem/openshift-preflight#734]
## Bug Description
preflight fails with error on RHEL 8.6

## Version and Command Invocation
preflight version 1.3.2 <commit: cfedcc7a46d47f9679eb137751ea22750d623c72>

## Steps to Reproduce:
(How can we reproduce this?)
1) Run it against any container image

## Expected Result
expect to pass, which is does but then it throws errors at the end of the test

## Actual Result
```
$ preflight-linux-amd64 check container <myimage>
time="2022-07-20T13:25:57-04:00" level=info msg="certification library version 1.3.2 <commit: cfedcc7a46d47f9679eb137751ea22750d623c72>"
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: HasLicense" result=PASSED
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: HasNoProhibitedPackages" result=PASSED
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-07-20T13:26:32-04:00" level=info msg="USER steamuser specified that is non-root"
time="2022-07-20T13:26:32-04:00" level=info msg="check completed: RunAsNonRoot" result=PASSED
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/policy/container.(*HasModifiedFilesCheck).dropFirstLayerIfEmpty(...)
	/go/src/preflight/certification/internal/policy/container/has_modified_files.go:108
github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/policy/container.(*HasModifiedFilesCheck).getDataToValidate(0x471753, {0x1b36f98, 0xc00011c000}, {{0x7ffcdd3cd4a4, 0x49}, {0xc0006f4400, 0x1c}, {0x1b6c248, 0xc0003ca180}, {0x7ffcdd3cd4b8, ...}, ...})
	/go/src/preflight/certification/internal/policy/container/has_modified_files.go:87 +0x557
github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/policy/container.(*HasModifiedFilesCheck).Validate(0x60, {0x1b36f98, 0xc00011c000}, {{0x7ffcdd3cd4a4, 0x49}, {0xc0006f4400, 0x1c}, {0x1b6c248, 0xc0003ca180}, {0x7ffcdd3cd4b8, ...}, ...})
	/go/src/preflight/certification/internal/policy/container/has_modified_files.go:31 +0x5e
github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/engine.(*CraneEngine).ExecuteChecks(0xc000136a00, {0x1b36f98, 0xc00011c000})
	/go/src/preflight/certification/internal/engine/engine.go:180 +0x162e
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd.preflightCheck({0x1b36f98, 0xc00011c000}, 0xc000028360, {0x0, 0x0}, {0x1b1fdf8, 0xc000136a00}, {0x1b24f30, 0xc0001c0de0}, {0x1b24f90, ...}, ...)
	/go/src/preflight/cmd/preflight_check.go:43 +0x2c2
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd.checkContainerRunE(0x2774700, {0xc0004a76c0, 0x1, 0x1})
	/go/src/preflight/cmd/check_container.go:99 +0x32a
github.com/spf13/cobra.(*Command).execute(0x2774700, {0xc0004a76a0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x2774e80)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd.Execute()
	/go/src/preflight/cmd/root.go:38 +0x58
main.main()
	/go/src/preflight/main.go:8 +0x17
```

## Additional Context
Running this on RHEL 8.6

**Comment by imperialguy** [comment]
Also, another question:

Looks like it is mandatory to have non-root user as default for the test to pass. If that's the case, then how do you propose that we start containers in `systemd` mode? Coz, containers don't start in `systemd` (even if the `entrypoint` explicitly tells them to), unless they are started as `root`.

**Comment by imperialguy** [comment]
Hello, any updates on this runtime error yet?

**Comment by komish** [comment]
Thanks for reporting this. Is the image you tested against accessible to us? The error seems to indicate that the issue may not be platform dependent. I'll test with other images as well to see if I can reproduce.

**Comment by komish** [comment]
Regarding:

> Looks like it is mandatory to have non-root user as default for the test to pass.

It's checked by default, but Preflight will check your Red Hat Container project for exception flags, such as the ability to run a privileged container, and will change what tests it runs accordingly. To do this, you'll need to provide Preflight a certification project ID and your pyxis API token at execution.

If those are not provided, then you get the default container policy, which includes the RunsAsNonRoot check.

**Comment by imperialguy** [comment]
> It's checked by default, but Preflight will check your Red Hat Container project for exception flags, such as the ability to run a privileged container, and will change what tests it runs accordingly. To do this, you'll need to provide Preflight a certification project ID and your pyxis API token at execution.

I do provide the project ID and pyxis token. My project is marked as unprivileged - means it doesn't require special host privileges or root to run it. When I say I want to run as root, I mean I want the container to be run as root inside, not outside.

So, it is rootless (outside) + root (inside). That's what I want. Can this be certified?

**Comment by imperialguy** [comment]
> Thanks for reporting this. Is the image you tested against accessible to us? The error seems to indicate that the issue may not be platform dependent. I'll test with other images as well to see if I can reproduce.

It's a private image hosted on gitlab. I can email you a temporary access token if you want to test it. Lemme know. 

And, even if the problem is not platform dependent and it has something to do with my image, I think it would be helpful if the runtime error is a bit more graceful. Coz, I would like to know what exactly is it with my image that it is complaining about in a more descriptive manner.

**Comment by imperialguy** [comment]
@komish 
I just emailed you the image link and gitlab access token. Please test it on your end and let me know what the issue is.

**Comment by komish** [comment]
@imperialguy We've just cut a release that should include the fix. Thanks again for your assistance with this. https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.3.3

**Comment by imperialguy** [comment]
@komish 
I just ran a test with the new one. PTAL at my observations below:

- When I marked the host level access in my project as "Unprivileged"

```
preflight-linux-amd64 check container </path/to/myregistry/image> -d /run/user/1000/containers/auth.json --pyxis-api-token=<mytoken> --certification-project-id=<mycertid>
Login Succeeded!
time="2022-07-26T19:37:44-04:00" level=info msg="certification library version 1.3.3 <commit: 6c30f7caae731ecc2faeaebd78c6d3981c708fe6>"
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: HasLicense" result=PASSED
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: HasNoProhibitedPackages" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="detected empty USER. Presumed to be running as root"
time="2022-07-26T19:38:06-04:00" level=info msg="USER value must be provided and be a non-root value for this check to pass"
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: RunAsNonRoot" result=FAILED
time="2022-07-26T19:38:16-04:00" level=info msg="check completed: HasModifiedFiles" result=PASSED
time="2022-07-26T19:38:16-04:00" level=info msg="check completed: BasedOnUbi" result=FAILED
```
**Problem**:
Now, I expect the `RunAsNonRoot` to fail, because my container runs as root (inside). But, why did `BasedOnUbi` fail? My container is 100% based on UBI.

- When I marked the host level access in my project as "Privileged"
```
preflight-linux-amd64 check container </path/to/myregistry/image> -d /run/user/1000/containers/auth.json --pyxis-api-token=<mytoken> --certification-project-id=<mycertid>
Login Succeeded!
time="2022-07-26T19:42:46-04:00" level=info msg="certification library version 1.3.3 <commit: 6c30f7caae731ecc2faeaebd78c6d3981c708fe6>"
time="2022-07-26T19:43:06-04:00" level=info msg="check completed: HasLicense" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasNoProhibitedPackages" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-07-26T19:43:17-04:00" level=info msg="check completed: HasModifiedFiles" result=PASSED
```
**Problem**:
All tests passed and I expect the `RunAsNonRoot` test to be skipped.  
But why did it also skip `BasedOnUbi` test? 

Also, as described above, my images are 100% based on ubi8. So, a.) It should run the `BasedOnUbi` test when the project is marked as `Privilged` and; b.) it should pass the `BasedOnUbi` test because my image is in fact based on ubi.
