### ISSUE TITLE
Add a Check to Verify that the RelatedImages Field Contains all Images for the Operator

### ISSUE THREAD

**Issue by jomkz** [redhat-openshift-ecosystem/openshift-preflight#740]
## Is your feature request related to a problem? Please describe.

We need to add a check that will scan the CSV for an operator and output any images that are referenced in the CSV but not listed in the `spec.relatedImages` field. This check will simply output a warning with the list of images not referenced in the `relatedImages` field for the OpenShift 4.11 release. With OpenShift 4.12, the check should fail if any images are not listed in the `relatedImages` field.

## Describe the solution you'd like.

Preflight should output the list of images as a warning that are not found in the `relatedImages` field in the CSV.

## Describe alternatives you've considered.

N/A

## Additional context.

N/A

**Comment by jomkz** [comment]
Is this already implemented in the operator certification pipeline?

**Comment by acornett21** [comment]
@amisstea Doesn't the `digest-pinning` task already make sure that there is a match of say count `spec.container.*.image` and `spec.relatedImages` and error if there is a miss-match?

**Comment by amisstea** [comment]
The hosted pipeline calls the pinning tool (https://github.com/containerbuildsystem/operator-manifest) and throws an error if modifications where made to any file. The tool doesn't have a verify mode or anything like that. Instead, we use the `pin` subcommand which populates `.spec.relatedImages` among other things. You may need to dig into the code of the tool to determine what it does regarding `spec.container.*.image`.
