### ISSUE TITLE
ubi check fails despite running against ubi-based image

### ISSUE THREAD

**Issue by imperialguy** [redhat-openshift-ecosystem/openshift-preflight#745]
@komish 
I just ran a test with the new one. PTAL at my observations below:

- When I marked the host level access in my project as "Unprivileged"

```
preflight-linux-amd64 check container </path/to/myregistry/image> -d /run/user/1000/containers/auth.json --pyxis-api-token=<mytoken> --certification-project-id=<mycertid>
Login Succeeded!
time="2022-07-26T19:37:44-04:00" level=info msg="certification library version 1.3.3 <commit: 6c30f7caae731ecc2faeaebd78c6d3981c708fe6>"
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: HasLicense" result=PASSED
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-07-26T19:38:05-04:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: HasNoProhibitedPackages" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-07-26T19:38:06-04:00" level=info msg="detected empty USER. Presumed to be running as root"
time="2022-07-26T19:38:06-04:00" level=info msg="USER value must be provided and be a non-root value for this check to pass"
time="2022-07-26T19:38:06-04:00" level=info msg="check completed: RunAsNonRoot" result=FAILED
time="2022-07-26T19:38:16-04:00" level=info msg="check completed: HasModifiedFiles" result=PASSED
time="2022-07-26T19:38:16-04:00" level=info msg="check completed: BasedOnUbi" result=FAILED
```
**Problem**:
Now, I expect the `RunAsNonRoot` to fail, because my container runs as root (inside). But, why did `BasedOnUbi` fail? My container is 100% based on UBI.

- When I marked the host level access in my project as "Privileged"
```
preflight-linux-amd64 check container </path/to/myregistry/image> -d /run/user/1000/containers/auth.json --pyxis-api-token=<mytoken> --certification-project-id=<mycertid>
Login Succeeded!
time="2022-07-26T19:42:46-04:00" level=info msg="certification library version 1.3.3 <commit: 6c30f7caae731ecc2faeaebd78c6d3981c708fe6>"
time="2022-07-26T19:43:06-04:00" level=info msg="check completed: HasLicense" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasNoProhibitedPackages" result=PASSED
time="2022-07-26T19:43:07-04:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-07-26T19:43:17-04:00" level=info msg="check completed: HasModifiedFiles" result=PASSED
```
**Problem**:
All tests passed and I expect the `RunAsNonRoot` test to be skipped.  
But why did it also skip `BasedOnUbi` test? 

Also, as described above, my images are 100% based on ubi8. So, 
a.) Shouldn't it be running the `BasedOnUbi` test when the project is marked as `Privilged` as well? and; 
b.) it should pass the `BasedOnUbi` test because my image is in fact based on ubi.

**Comment by bcrochet** [comment]
Can you upload the output from:

`podman image inspect quay.io/bcrochet/container-passes | jq '.[].RootFS'`

**Comment by imperialguy** [comment]
Here:
```
{
  "Type": "layers",
  "Layers": [
    "sha256:3c9205208d5414d089f6885fba43ae3c843b08f2a5ea0731f402c922ecc128d3"
  ]
}
```

**Comment by lslebodn** [comment]
```
{
  "Type": "layers",
  "Layers": [
    "sha256:3c9205208d5414d089f6885fba43ae3c843b08f2a5ea0731f402c922ecc128d3"
```
If your image is based on UBI than please do not squash layers to single one.

You can squash layers which you use for building your images.
But layers for parent/base UBi iamge must be unchanged.

**Comment by acornett21** [comment]
@imperialguy Like @lslebodn mentioned, you cannot modify UBI layers/files/etc, please see the follow [link](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.45/html/red_hat_openshift_software_certification_policy_guide/assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction) for all of the container certification polices to make sure your image complies.

**Comment by imperialguy** [comment]
Okay, assuming I don't squash them, will this check also be added to Privileged containers?

**Comment by acornett21** [comment]
@imperialguy Yes, UBI check was missed in a refactor, it's been added back to `main`. If you want to build from main to test, feel free. We should have a release with this in the next few days.

**Comment by imperialguy** [comment]
Gotcha. Cool. just tested with layers intact. it passes. will wait for the next release to test against privileged. Thanks.

**Comment by acornett21** [comment]
@imperialguy We have [released](https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.3.4) a fix to add back in the UBI check for `Privileged` containers. Let us know if you have any more issues.

**Comment by acornett21** [comment]
- Relates: #746
