### ISSUE TITLE
[ suggestion ] create a framework of parsing operator bundle contents

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#752]
**Abstract**:

Recent feature requests, require parsing and fetching information from CSV.
later features may require parsing other manifests in the bundle, as well as annotations yaml etc'.

Currently, each new check would need to have all the logic of reading, unmarshalling and fetching a specific block of information from the bundle, and then applying rules to it.

this suggestion should make implementation of new checks in the bundle area (as they come up) easier, by having the check itself only need to apply the rules.

**Solution suggestion**:

Leverage the structure created by Operator Framework and used in `operator-sdk bundle validate` flow (for example).
if possible by importing it as a lib.  if not, by defining structs.

**Reference** - https://github.com/operator-framework/api/blob/master/pkg/operators/v1alpha1/clusterserviceversion_types.go

**Comment by bcrochet** [comment]
This would be an ideal candidate to contribute to:

https://github.com/operator-framework/operator-manifest-tools

**Comment by bcrochet** [comment]
Closing this. I think we have quite a bit of this already from the above mentioned repo, and from https://github.com/operator-framwork/api.
