### ISSUE TITLE
Preflight instability issues

### ISSUE THREAD

**Issue by wcheang** [redhat-openshift-ecosystem/openshift-preflight#753]
## Bug Description
Recently the operator hosted pipeline runs have run into occasional issues running preflight, which recovers after a re-run. Examples of failed runs:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.9-preflight-common-claim/1554818603017048064
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.9-preflight-common-claim/1554822426376802304

While re-running does get preflight to pass eventually, the initial failures can cause confusion to users, so it'll be good if the failures are investigated.

## Version and Command Invocation
Version 1.2.0
Container image used:  quay.io/redhat-isv/preflight-test@sha256:fba6919bfb5c647877453dd948b1e7d3394c4573482e3776ae9a85abd70f912e

## Steps to Reproduce:
(How can we reproduce this?)
This seems to be happening randomly, so I don't know how to reproduce it yet.

## Expected Result
Preflight passes if there is nothing wrong with the bundle image being tested.

## Actual Result
Preflight occasionally fails from errors unrelated to the bundle image.

## Additional Context
This is running on OpenShift Dedicated 4.10, by the operator hosted pipeline.

**Comment by acornett21** [comment]
@wcheang Thanks for raising this issue, we do look at failures and an enhancement recently went into openshift/releases

- Relates: openshift/release#31042

If you see this issue again can you raise a Jira to the `ISVISSUE` board so we can track it better? Thanks!

**Comment by wcheang** [comment]
Will do. Thank you for the quick response!
