### ISSUE TITLE
Implement deliverables for multiple architectures

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#76]
Reference:  
- https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04
- https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63

- [ ] make build for:  linux-amd64,  darwin-amd64, zos-s390x, linux-ppc64, darwin-arm64 (Apple M1) ?,  windows-amd64 ? 
- [ ] make image-build for:  linux-amd64,  darwin-amd64, zos-s390x, linux-ppc64, darwin-arm64 (Apple M1) ?,  windows-amd64 ? 
- [ ] add a test to run each binary on the appropriate architecture into CI [proposed Label] kind/design

**Comment by jomkz** [comment]
@itroyano Will the work for this issue be addressed by #371?

**Comment by jomkz** [comment]
Closing this issue as it should be fixed by #371.
