### ISSUE TITLE
provide more accurate details of DeployableByOLM failure in preflight.log

### ISSUE THREAD

**Issue by maratsal** [redhat-openshift-ecosystem/openshift-preflight#769]
## Is your feature request related to a problem? Please describe.
Currently when preflight tool is trying to install operator within `DeployableByOLM` test, if installation fails preflight logs don't provide enough information for troubleshooting. It gets messages only from installed CSV - please check the code https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/786f9be6f3e0d0245755cf68e29df5865025b871/certification/internal/policy/operator/deployable_by_olm.go#L497-L517

Unfortunately that is not enough sometimes, in addition to those CSV messages it would be great to log subscription `status.Conditions` field details as well.

Here is example of that section of the subscription:
```
  Conditions:
    Last Transition Time:   2022-08-11T03:33:19Z
    Message:                all available catalogsources are healthy
    Reason:                 AllCatalogSourcesHealthy
    Status:                 False
    Type:                   CatalogSourcesUnhealthy
    Last Transition Time:   2022-08-11T03:34:54Z
    Message:                error updating service: my-long-prefix-that-cause-failure-controller-manager-metrics-service: Service "my-long-prefix-that-cause-failure-controller-manager-metrics-service" is invalid: metadata.name: Invalid value: "my-long-prefix-that-cause-failure-controller-manager-metrics-service": must be no more than 63 characters
    Reason:                 InstallComponentFailed
    Status:                 True
    Type:                   InstallPlanFailed
```

To be able to catch this we need to monitor subscription manually during the test (or during manual operator deployment) and capture status of the subscription.

## Describe the solution you'd like.
in addition to those CSV messages it would be great to log subscription `status.Conditions` field details as well.

## Describe alternatives you've considered.
To be able to catch this we need to monitor subscription manually during the test (or during manual operator deployment) and capture status of the subscription.

## Additional context.
N/A

**Comment by tkrishtop** [comment]
Some additional info: the logs are displaying `sub.Status`

https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/786f9be6f3e0d0245755cf68e29df5865025b871/certification/internal/policy/operator/deployable_by_olm.go#L487 

Here is an example from the [job failing DeployableByOlm](https://www.distributed-ci.io/jobs/e98d10cf-cfd9-41fa-9115-b04f3d9f09ed/tests).

```
time="2022-08-18T08:16:55Z" level=trace msg="current subscription status is 
{CurrentCSV: InstalledCSV: Install:<nil> State: Reason: InstallPlanGeneration:0 InstallPlanRef:nil CatalogHealth:
[
{CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:keysight-websocket-service,Name:keysight-websocket-service,UID:f8c74b26-cf51-4002-ae38-9f7c8385545e,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13788973,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true} {CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:openshift-marketplace,Name:certified-operators,UID:43322923-059b-4a6b-b8c0-c439d00f3b3a,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13787491,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true} 
{CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:openshift-marketplace,Name:community-operators,UID:9cc30373-5605-4493-b8cf-be9c0929c055,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13787738,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true} 
{CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:openshift-marketplace,Name:loadcore-catalog,UID:67795557-16a9-48c2-a7c6-6f6d43f1d2c6,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13785270,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true} 
{CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:openshift-marketplace,Name:redhat-marketplace,UID:a0996811-1064-4406-8f70-69139b54b852,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13786165,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true} 
{CatalogSourceRef:&ObjectReference{Kind:CatalogSource,Namespace:openshift-marketplace,Name:redhat-operators,UID:803ee3f7-db39-4708-b250-eba3e7f5f1e7,APIVersion:operators.coreos.com/v1alpha1,ResourceVersion:13785799,FieldPath:,} LastUpdated:2022-08-18 08:13:58 +0000 UTC Healthy:true}] 
Conditions:[{
Type:CatalogSourcesUnhealthy 
Status:False 
Reason:AllCatalogSourcesHealthy 
Message:all available catalogsources are healthy 
LastHeartbeatTime:<nil> LastTransitionTime:2022-08-18 08:13:58 +0000 UTC}] 
LastUpdated:2022-08-18 08:13:58 +0000 UTC}"
```

and that includes `sub.Status.Conditions` already

```
Conditions:[{Type:CatalogSourcesUnhealthy 
Status:False 
Reason:AllCatalogSourcesHealthy 
Message:all available catalogsources are healthy 
LastHeartbeatTime:<nil> 
LastTransitionTime:2022-08-18 08:13:58 +0000 UTC}]
```

It seems that the `Conditions` array somehow always displays only the first element, and the second one, with the actual error and useful debug message, is somehow missing

```
  Conditions:
    Last Transition Time:   2022-08-11T03:33:19Z
    Message:                all available catalogsources are healthy
    Reason:                 AllCatalogSourcesHealthy
    Status:                 False
    Type:                   CatalogSourcesUnhealthy
    Last Transition Time:   2022-08-11T03:34:54Z
    Message:                error updating service: my-long-prefix-that-cause-failure-controller-manager-metrics-service: Service "my-long-prefix-that-cause-failure-controller-manager-metrics-service" is invalid: metadata.name: Invalid value: "my-long-prefix-that-cause-failure-controller-manager-metrics-service": must be no more than 63 characters
    Reason:                 InstallComponentFailed
    Status:                 True
    Type:                   InstallPlanFailed
```

**Comment by maratsal** [comment]
@tkrishtop you are right, it is posting subscription status to the logs, however it does it only till operator gets installed CSV details, as soon as CSV is installed preflight is focused on the CSV and keep checking its status till it becomes ready.

And during CSV installation time subscription status gets more details about actual failure.

Right before finishing DeployableByOLM check, in addition to watcher messages, it would be great to add status of subscription with actual error message of the failure from conditions section of subscription status.

**Comment by acornett21** [comment]
We might be able enhance this, but it's still hard to trap all the errors that can happen in an OLM operator install. They could be in the SUB, or in Events, or in the Container, or anywhere really. We can't watch the entire cluster.

My question is why is `preflight` being used to iteratively develop operators? Operator developers should, build, run, test, and deploy their operators to a cluster both natively (make run), and as bundles (but preferably via custom catalogs) before preflight even is involved in the process.

In my opinion `preflight` should be the _last_ step in the process above, not the _first_.

**Comment by tkrishtop** [comment]
@maratsal the example you provided fails waiting for the subscription, not CSV: `prod.harbor.xxx.digital/xxx/xxx-wap-stats-dashboards-bundle:latest`. In that case, the existing logs are already providing all the required info and my PR has no added value.

```
Conditions:[{
Type:CatalogSourcesUnhealthy 
Status:False Reason:AllCatalogSourcesHealthy 
Message:all available catalogsources are healthy 
LastHeartbeatTime:<nil> 
LastTransitionTime:2022-08-20 14:13:57 +0000 UTC} 
{
Type:InstallPlanPending 
Status:True 
Reason:Installing 
Message:unpack job not completed: Unpack pod(xxx-wap-stats-dashboards/92e01d2544f76ec2b0b846bbc82785e0c0b4a68dfe31de8c487862a28frnv48) container(pull) is pending. 
Reason: ImagePullBackOff, 
Message: Back-off pulling image \"prod.harbor.xxx.digital/xxx/xxx-wap-stats-dashboards-bundle:latest\". 
LastHeartbeatTime:<nil> 
LastTransitionTime:2022-08-20 14:16:16 +0000 UTC
}] 
LastUpdated:2022-08-20 14:16:16 +0000 UTC}"
```

**Comment by maratsal** [comment]
@tkrishtop your failure case is different than my test case. I will show you on Monday what exactly happens in my test case.

**Comment by tkrishtop** [comment]
@acornett21 

> it's still hard to trap all the errors that can happen in an OLM operator install

If we have a failing test DeployableByOlm, the info about why it's failing should be available in the logs.

**Comment by bcrochet** [comment]
Preflight is not a debugging tool. It is a certification tool. Not sure if we should be using your example as an actual failure case, but if it is, why are you knowingly sending invalid things to preflight? As @acornett21 said, you should be sending what you believe to be a known *good* bundle to preflight, not using preflight to run known *failing* tests. If that's how you are using it, you should be monitoring your cluster for events outside of preflight anyway.

**Comment by maratsal** [comment]
@bcrochet @acornett21 I partially agree and disagree :)

I agree that we should be catching this kind of issue on the earlier stage of our development and build process, however I still believe that preflight.log should be catching those errors from subscription status section in addition to the info it is already capturing, without that information I feel that preflight logs are not useful enough, as we are forced to do additional manual checks.

**Comment by bcrochet** [comment]
> @bcrochet @acornett21 I partially agree and disagree :)
> 
> I agree that we should be catching this kind of issue on the earlier stage of our development and build process, however I still believe that preflight.log should be catching those errors from subscription status section in addition to the info it is already capturing, without that information I feel that preflight logs are not useful enough, as we are forced to do additional manual checks.

The preflight logs are primarily for debugging preflight, not the operator under test. IIUC, you are sending known bad data to preflight. What you are describing is not a preflight failure. It's bad input.

I'm curious how this is even making it past the BundleValidate call at the beginning of DeployableByOLM. I can't reproduce your failure. When I try it, the BundleValidate call at the beginning of DeployableByOLM spits out an error, and doesn't proceed.

**Comment by maratsal** [comment]
Here is another issue I have created for this specific error, but around operator-sdk - https://github.com/operator-framework/operator-sdk/issues/5988

for some reason `operator-sdk validate` doesn't catch the problem either, and there you have steps on how to reproduce it.

**Comment by bcrochet** [comment]
Which version of operator-sdk are you using? I am seeing it being caught with 1.22.2.

**Comment by bcrochet** [comment]
> Here is another issue I have created for this specific error, but around operator-sdk - [operator-framework/operator-sdk#5988](https://github.com/operator-framework/operator-sdk/issues/5988)
> 
> for some reason `operator-sdk validate` doesn't catch the problem either, and there you have steps on how to reproduce it.

❯ operator-sdk bundle validate ./bundle
ERRO[0000] Error: Value : (my-long-prefix-that-cause-failure-controller-manager-metrics-service) metadata.name "my-long-prefix-that-cause-failure-controller-manager-metrics-service" is invalid: must be no more than 63 characters

**Comment by maratsal** [comment]
I have the same version 1.22.2
```
 $ operator-sdk init --plugins helm --domain mydomain.com --group mygroup --version v1alpha1 --kind Nginx --helm-chart=bitnami/nginx --project-name my-random-long-project-name-nginx^C
 $ operator-sdk init --plugins helm --domain mydomain.com --group mygroup --version v1alpha1 --kind Nginx --helm-chart=bitnami/nginx --project-name my-random-long-project-name-nginx
Writing kustomize manifests for you to edit...
Creating the API:
 $ /usr/local/Cellar/operator-sdk/1.22.2/libexec/bin/operator-sdk create api --group mygroup --version v1alpha1 --kind Nginx --helm-chart bitnami/nginx
Writing kustomize manifests for you to edit...
Created helm-charts/nginx
Generating RBAC rules
I0824 14:20:44.486094   85099 request.go:601] Waited for 1.049068512s due to client-side throttling, not priority and fairness, request: GET:https://api.lab.ocp.lan:6443/apis/storage.k8s.io/v1?timeout=32s
WARN[0021] The RBAC rules generated in config/rbac/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in config/rbac/role.yaml to ensure they meet the operator's permission requirements. 
 $ make bundle
operator-sdk generate kustomize manifests -q

Display name for the operator (required): 
> nginx operator

Description for the operator (required): 
> nginx operator

Provider's name for the operator (required): 
> nginx operator

Any relevant URL for the provider name (optional): 
> 

Comma-separated list of keywords for your operator (required): 
> nginx

Comma-separated list of maintainers and their emails (e.g. 'name1:email1, name2:email2') (required): 
> marat@mydomain.com
cd config/manager && /usr/local/bin/kustomize edit set image controller=controller:latest
/usr/local/bin/kustomize build config/manifests | operator-sdk generate bundle -q --overwrite --version 0.0.1  
INFO[0000] Creating bundle.Dockerfile                   
INFO[0000] Creating bundle/metadata/annotations.yaml    
INFO[0000] Bundle metadata generated suceessfully       
operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully 
 $ operator-sdk bundle validate ./bundle
INFO[0000] All validation tests have completed successfully 
 $ operator-sdk version
operator-sdk version: "v1.22.2", commit: "da3346113a8a75e11225f586482934000504a60f", kubernetes version: "v1.24.1", go version: "go1.18.4", GOOS: "darwin", GOARCH: "amd64"
 $
```

**Comment by bcrochet** [comment]
I do not feel this is a bug in preflight. You are artificially creating this scenario. If you'd like to make a pull request, we will review it. But I don't feel this is something we will be looking at implementing at this time.

**Comment by maratsal** [comment]
It is not artificially created, I faced this issue during the development of the operator from the helm chart and running through certification process.

As I told previously, I totally agree that this should be caught on earlier stage of the development and testing process, however I still believe preflight logs should be having more details that would help troubleshooting of not passing `DeployableByOLM` test.

**Comment by itroyano** [comment]
Hi @maratsal, there may be some confusion here.
Preflight is a certification tool.
during development, tools provided by Operator Framework such as `operator-sdk bundle validate`  and `make bundle/deploy` should be used.

**Comment by maratsal** [comment]
@itroyano there is no confusion here.

I understand that we should be catching this issue on earlier stage of our development. Also I am not coming from artificially made up theoretical scenario like @bcrochet mentioned. What we were doing is creating helm based operator in automated way from currently available helm charts and afterwards certifying it. This particular issue should be caught by `operator-sdk bundle verify` command that is used in development/build process, however for some unknown reasons it doesn't happen (I have created separate issue for operator-sdk to address that). We are currently still in development of the part of pipeline that would be deploying and testing operator functionality and it will be done before preflight. Unfortunately it has happened that this issue because of those reasons got up to preflight tool steps where I realized that having more verbose logs would useful and allow developers to use logs and not going back to the OCP cluster and checking the reasons of failure.

All my intension was to make tool better and more user friendly. If tool's developers decided this is not useful - I am ok with that too.

**Comment by itroyano** [comment]
Thanks for clarifying the use case, @maratsal.
I'm less aware of automated ways to fully create an Operator - rather than just using the development tools of Operator Framework to create a scaffold, and then filling in the code - but I still view that as a development process.
one that should be using development tools.
in case the development tool has a gap, it's best to raise that vs. the relevant team like you did.
Preflight isn't aiming to replace the development tool, or give development-level feedback.
if `DeployableByOLM` fails then local deployment troubleshooting should commence to understand why the operator cannot be successfully deployed.
