### ISSUE TITLE
[ Check ] Operator Catalog initialization test

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#78]
Reference: https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/blob/master/roles/operator_catalog_initialization_test/tasks/main.yml

Proposed implementation:
- Add a user flag for providing KUBECONFIG (in case it wasn't added yet).
- Define the check as runnable for Bundle Images
- Use `ExtractContainerTar` to obtain manifests
- Run `catalog initializer` and add RC and output into `results`.

**Comment by itroyano** [comment]
@samira-barouti  The DeployableByOLM test you've added,  adds a framework for interacting with OLM and Catalog.
does it simplify implementing the above?  
(please see main yaml Ansible role in the link)

**Comment by samira-barouti** [comment]
@itroyano The Deployable By OLM check adds k8s clients to interact with API server and create custom resources (CatalogSource, OperatorGroup and Subscription). However, it does not perform index image creation from the bundle; the hosted pipeline is taking care of this activity and will set environment variable to pass along the index image URI to the preflight.

**Comment by itroyano** [comment]
/descoped.   
per Brian Cook this isn't required to be a standalone test, when Depoyable By OLM exists.
