### ISSUE TITLE
Checking a local container (instead of a container in a registry)

### ISSUE THREAD

**Issue by fhennig** [redhat-openshift-ecosystem/openshift-preflight#896]
## Is your feature request related to a problem? Please describe.
We would like to check container builds in a CI, before we push them. A container should only be published if the preflight check succeeds. Pushing a container that later turns out to be non-compliant is not good.

## Describe the solution you'd like.
It seems like preflight always tries to pull containers, I'd like a way for it to check locally if the image is already present.

## Describe alternatives you've considered.
-

## Additional context.
-

**Comment by acornett21** [comment]
- Relates: #593

**Comment by fhennig** [comment]
Thanks for your quick response! 

I see in the ticket you linked that enabling this would require some fundamental changes, that's unfortunate. Thanks for the workaround I'll see how we'll move forward! :+1:
