### ISSUE TITLE
Warn about low freshness grade layers when checking a container

### ISSUE THREAD

**Issue by itroyano** [redhat-openshift-ecosystem/openshift-preflight#937]
## Is your feature request related to a problem? Please describe.
A partner would like to get a sense of the approximate Security Scanner score they could get, while doing a container check.
Avoiding a low score before publishing.

## Describe the solution you'd like.
Since we already check the layers - we could warn if a lower grade layer is being used, allowing the partner to increment that and increase their chances of getting a good score.

**Comment by bcrochet** [comment]
This is also something the partner can implement on their own within their own CI/CD pipeline with Pyxis. We would not be able to give them an on-the-spot grade, and merely report back what the grade of the other layers within their image would be. They have access to the same information from Pyxis that preflight would. There is not a good reporting mechanism to implement this. I will leave this open for a week or so for additional comment, but this is likely to be closed.

**Comment by itroyano** [comment]
That's the "official" answer I gave to the partner - they can interact with Pyxis from their CI.
But in my opinion there is a learning curve to doing that, for a partner that's not familiar with Pyxis' APIs.
I'm not expecting Preflight to grade their image. That's not what it's designed for.
But we do fetch layers from Pyxis and therefore can decide to throw a warning if - at the time of fetching - one or more layers are currently grade E or below for example.
It's a QoL for the partner in my opinion, to be able to get notified. Even via log in case of no better options.

**Comment by lslebodn** [comment]
> therefore can decide to throw a warning 

Warning might be OK; because users might update packages from base image with `*dnf update`
They sometime need to do it when base image has not been updated yet but RPM for CVE is already available in repositories

**Comment by itroyano** [comment]
@acornett21 it may be down to wording, or choosing to do an INFO vs. a WARN etc'.
Clair scans the finalized image, and we aren't "competing" with it.
But it's reasonable to assume IMO that an image using an F grade base layer, won't end up getting an A from Clair.
So wording it like a "might get a low grade, please take a look" is a QoL.

**Comment by acornett21** [comment]
We decided that this should not live in preflight, but a partner can make a curl to get this info from pyxis. See below:

```
export PYXIS_API_TOKEN="..."
export CONTAINER_SHA="sha256:..."
curl -s -X 'GET' 'https://catalog.stage.redhat.com/api/containers/v1/images?filter=docker_image_digest=='"${CONTAINER_SHA}"'&page_size=100&page=0' \
  -H 'accept: application/json' \
  -H 'X-API-KEY: '"${PYXIS_API_TOKEN}"'' | jq '{id: .data[0]._id, freshness_grades: .data[0].freshness_grades[] | {grade, creation_date}}' 
  ```
