### ISSUE TITLE
Support running preflight with manifest list

### ISSUE THREAD

**Issue by lucacome** [redhat-openshift-ecosystem/openshift-preflight#955]
## Is your feature request related to a problem? Please describe.
Since https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/807 was closed I'm opening a new issue as it was never resolved.

We need to certify our image for multiple architectures and we're running `preflight` manually multiple times. This is time-consuming and error-prone.

From the manifest list in the registry is possible to extract all the architectures and submit them programmatically (since the backend doesn't support manifest list)

## Describe the solution you'd like.
I would like to be able to run `preflight` with an image and have all the architectures for that image verified.

## Describe alternatives you've considered.
Running `preflight` for each architecture passing the `--platform` flag

**Comment by bcrochet** [comment]
For which operation are you wanting this? `check operator` or `check container`? 

We have limitations on what we can do in this regard, due to limitations in upstream systems.

**Comment by lucacome** [comment]
@bcrochet this request is for `check container`. Are you talking about the limitation on the backend as mentioned here https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/807#issuecomment-1285636929 ?
If so, isn't it possible to just loop through all the architectures and submit them individually, like somebody would _manually_ do right now?

**Comment by bcrochet** [comment]
> @bcrochet this request is for `check container`. Are you talking about the limitation on the backend as mentioned here [#807 (comment)](https://github.com/redhat-openshift-ecosystem/openshift-preflight/issues/807#issuecomment-1285636929) ? If so, isn't it possible to just loop through all the architectures and submit them individually, like somebody would _manually_ do right now?

That is what I'm referring to, correct.

I guess I'm unsure why you consider it manual? For one, it would not save any time to have preflight do the loop as opposed to a script for instance. Preflight would still be executed n times.

```bash
for platform in amd64 arm64; do
  preflight check container --platform ${platform} supercoolcontainer
done
```

If I'm missing something about this, please correct me.

**Comment by lucacome** [comment]
I consider it manual because we need to remember to certify every architecture or write a script with a list of the architectures that need to be updated if we add a new one (even if that's a rare case).

I think it would make more sense for `preflight` to do this in code and it would also remove the need for an additional flag. I just think of my image as one, not individual images of all the architectures. I'm not worried about the number of requests the tool makes.

And if the backend will start supporting manifest lists, the behavior from the user's perspective will remain the same.

**Comment by lucacome** [comment]
@bcrochet that's right it's a manifest list (or OCI index). I point to the index and use `--platform` for every architecture in the index.

example:

```
preflight check container docker.io/nginx/nginx-ingress:3.1.1-ubi --platform amd64 --pyxis-api-token <token> -s --certification-project-id <project-id>
```
