### ISSUE TITLE
Using customised issue template for the repository

### ISSUE THREAD

**Issue by vikasmulaje** [redhat-openshift-ecosystem/openshift-preflight#97]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

While filing bugs/RFE if we have customised template it will be easier for Getting all the required information.
This will be helpful for identifying root cause and saves time for getting required information for debugging

**Comment by komish** [comment]
@vikasmulaje Thanks for filing this issue! I'll work on getting this adding ASAP.

/assign
/kind feature
