### ISSUE TITLE
HasMinimalVulnerabilitiesCheck OVAL definitions may need to change based on the input image

### ISSUE THREAD

**Issue by komish** [redhat-openshift-ecosystem/openshift-preflight#99]
Mentioned in the 2021-07-15 community meeting, the OVAL file used for the HasMinimalVulnerabilitiesCheck will need to changed to match the underlying base image. 

Currently we utilize the RHEL-8 definition (see https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/f1a21ac79bfc854639ffed1e7f4cbe0e526aa11d/certification/internal/shell/podman.go#L20-L21) in the current implementation, and that applies to all images. This may not be the desired outcome for all submitted/tested images.

**Comment by bcrochet** [comment]
Going to disable this check for now.

**Comment by bcrochet** [comment]
Yes please. Let's get a separate issue to track the full removal.

**Comment by jomkz** [comment]
I have created #381 to track the work to remove HasMinimalVulnerabilitiesCheck, closing this issue.
